### ISSUE TITLE
GraphQL API content does not appear to explain required permissions

### ISSUE THREAD

**Issue by jsoref** [github/docs#8925] opened 2021-08-10 03:33 UTC
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's Code of Conduct.

### What article on docs.github.com is affected?

https://docs.github.com/en/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql

### What part(s) of the article would you like to see updated?

#authenticating-with-graphql

The section that talks about authentication really doesn't help understand what permissions one needs to do things

A [forum post](
https://github.community/t/allow-the-github-token-to-also-have-rights-for-converting-prs-to-draft-or-vice-versa/194555
) asked about converting a PR to/from draft.

### Additional information

The v3 API has a long page that makes it possible to try to figure out what permissions one might need:
https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-pull-requests

But, I really can't find any equivalent for the v4 api.

For reference, here's the mutation in question:
https://docs.github.com/en/graphql/reference/mutations#convertpullrequesttodraft

**Comment by Slack88** [comment] 2021-09-28 18:32
Może być to zażadza

**Comment by hubwriter** [comment] 2021-10-04 11:02
@jsoref - Thank you for raising this issue. 

I've had a look at this and I think the problem here lies not with the authentication information on the page you refer to (https://docs.github.com/en/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql) but with the problem using the `GITHUB_TOKEN` to update a PR's status (as described in this discussion: https://github.com/github/feedback/discussions/5082). 

The GraphQL documentation page says that the scopes your token requires "depends on the type of data you're trying to request". Although this is vague, I think it's enough to allow people to choose the appropriate scopes when they create a token because the scopes are quite clearly described in the user interface for creating a token.

In referring to the "[Permissions required for GitHub Apps](https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-pull-requests)" article in the REST API documentation, as an example of what we might do for GraphQL, I don't believe you're comparing like with like. 

I will raise [Discussion 5082](https://github.com/github/feedback/discussions/5082) with our Actions team. 

Thanks again for raising this issue.

**Comment by lee-dohm** [comment] 2021-10-04 17:01
Thanks for the feedback. Given that we've raised this internally, we're going to close this issue. Please note, we can't promise when or even if this will be addressed but we have brought it to the attention of the proper team.

Thanks again!

**Closed by lee-dohm** 2021-10-04 17:01 UTC
Labels: content

**Comment by evpaassen** [comment] 2021-11-16 15:23
GitHub support just confirmed:
> This feature is currently not available to server-to-server tokens. We have an internal issue tracking this as a feature request and I'd be happy to add this report to the list.
