### ISSUE TITLE
Description of rebase merge method is incorrect

### ISSUE THREAD

**Issue by spikyjt** [github/docs#1387] opened 2020-11-16 13:55 UTC
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-merge-methods-on-github

Contained in:
https://github.com/github/docs/blob/main/content/github/administering-a-repository/about-merge-methods-on-github.md

Which reads from:
https://github.com/github/docs/blob/main/data/reusables/pull_requests/rebase_and_merge_summary.md

### What part(s) of the article would you like to see updated?

In the section `Rebasing and merging your commits`, the description says
> Pull requests with rebased commits are merged using the fast-forward option.

However, this is not the case. Rebasing is actually done with the `--force` option as described later in the section where it clarifies that the commit hash and the committer will change. This is explicitly forced rebase behaviour and quite different from fast-forward, which leaves all commits as-is.

### Additional information

I consider this confusing, as someone looking for a fast-forward merge option might stop at the end of the intro, thinking they have found the option they need, but in fact will get different behaviour.

**Comment by bk2204** [comment] 2020-11-19 20:26
Hey,

I've looked at what's going on here, and you're correct that the committer information is updated to reflect the person performing the merge.  I'm not sure, but I think what might have been intended by this is that the branch is rebased by the person doing the merge and then merged into the base branch with `git merge --ff-only`, which, while technically accurate, is a little confusing.

I agree that things could be rephrased to be a little clearer here about the behavior.

**Comment by ramyaparimi** [comment] 2021-09-29 17:40
@spikyjt Sorry for the delay 💛  @bk2204 explained the expected behavior ✨ You or anyone is welcome to open a PR clarifying the behavior in the article. 💖

**Closed** 2021-11-04 16:07 UTC
Labels: help wanted, content
