### ISSUE TITLE
Adding license after making repo is not populating on add file manually

### ISSUE THREAD

**Issue by lexcraw4d** [github/docs#7523] opened 2021-06-20 09:15 UTC
### What article on docs.github.com is affected?

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

### What part(s) of the article would you like to see updated?

I am trying to add a license to an old repo and they aren't showing up like they used to on the right side when you created a file from your  repo hard coded and typed LICENSE as the file name or LICENSE.md, whereas there use to be a place where it populated after you typed this. Any advice? The current documentation for this is not working.

### Additional information
Using Chrome

**Comment by fnise-urt** [comment] 2021-06-20 19:27
I was unable to reproduce.

- create a new repo
- upload some files

I added the LICENSE to the main branch.

After reloading the page  the name of the selected license appeared in the right sidebar.

**Comment by lexcraw4d** [comment] 2021-06-21 01:57
I am trying to add it to a preexisting repo and it is not populating.

**Comment by janiceilene** [comment] 2021-06-22 18:31
I'm not sure @lexcraw4d, this would probably be best answered by our wonderful [support team](https://support.github.com/contact) 💛 

I'm going to close this issue now, since there's not a current request for an update to docs.github.com, but if you figure out what's happening and see a need for a docs update, let us know!

**Closed by janiceilene** 2021-06-22 18:31 UTC
Labels: content, triage
