### ISSUE TITLE
I'll open an issue and propose an addition to the Style Guide, coming soon!

### ISSUE THREAD

**Issue by DiKarat** [github/docs#6011] opened 2021-05-04 04:53 UTC
I'll open an issue and propose an addition to the Style Guide, coming soon!

_Originally posted by @jai in https://github.com/github/docs/issues/5945#issuecomment-831635058_

**Comment by jai** [comment] 2021-05-04 04:55
whoops - possible duplicate of https://github.com/github/docs/issues/6009 (I opened #6009) based on the same thread

Also PR: https://github.com/github/docs/pull/6010

**Closed** 2021-05-04 16:29 UTC
Labels: invalid, triage
