### ISSUE TITLE
`note` tags reset ordered list numbering

### ISSUE THREAD

**Issue by jeffmaher** [github/docs#1552] opened 2020-11-22 19:41 UTC
### What is the current behavior?

It seems that `{% note %}` / `{% endnote %}` tags reset number when rendered in docs pages. This behaviour manifests in the final generated page, although it does not appear in the GitHub web editor preview tab.

An example page is:

- Rendered: https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-gpg-key
- Markdown: https://github.com/github/docs/blob/main/content/github/authenticating-to-github/generating-a-new-gpg-key.md

The numbering reset is visible after the first `note` and after any subsequent `note`.

![Screen Shot 2020-11-22 at 14 38 00](https://user-images.githubusercontent.com/950486/99915247-90daa500-2cd0-11eb-9306-659c5eaef444.png)

### What changes are you suggesting?

Allow ordered list numbering to continue past a `note`.

### Additional information

If there's any other info I can provide, let me know.

**Comment by janiceilene** [comment] 2020-11-23 20:14
Thanks so much for opening an issue @jeffmaher! There was an internal PR that was causing <li> elements to break when there were notes between steps. The PR was reverted and this article looks right to me now, so I'm going to close this out 🎉 

Feel free to re-open if the issue isn't resolved or if I misunderstood.

**Closed by janiceilene** 2020-11-23 20:14 UTC
Labels: engineering, triage
