### ISSUE TITLE
GitHub docs pull dark mode settings from multiple sources

### ISSUE THREAD

**Issue by skedwards88** [github/docs#23131] opened 2023-01-11 00:30 UTC
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

If your system color is set to dark mode but your GitHub preferences are set to light mode, the docs render part dark/part light.

<img width="718" alt="image" src="https://user-images.githubusercontent.com/25328854/211690131-9454c42b-ff59-417c-90d6-9c43a51893a0.png">

### What changes are you suggesting?

Use dark mode settings from a consistent source.

### Additional information

Originally reported by @rattrayalex

**Comment by cmwilson21** [comment] 2023-01-11 14:53
👋 @skedwards88 - Thanks for opening this! I'll get it triaged 💖

**Comment by peterbe** [comment] 2023-01-12 13:16
Can we now close this as a dupe of https://github.com/github/docs-engineering/issues/2098 ?

**Comment by peterbe** [comment] 2023-01-13 15:07
Let's close this and focus on the original issue.

**Closed by peterbe** 2023-01-13 15:07 UTC
Labels: engineering
