### ISSUE TITLE
Improving content: Create a Windows Credential Manager documentation page

### ISSUE THREAD

**Issue by casals** [github/docs#698] opened 2020-10-21 18:11 UTC
This issue is a partial breakdown from issue #429 (see [this comment](https://github.com/github/docs/issues/429#issuecomment-709217217)).

### What article on docs.github.com is affected?

Currently there's a topic to help macOS users update their credentials: [Updating credentials from the macOS Keychain](https://docs.github.com/en/free-pro-team@latest/github/using-git/updating-credentials-from-the-macos-keychain) . The sub-issue here is the need for a Windows Credential Manager documentation page to complement this content.

### What part(s) of the article would you like to see updated?

This requires a new article. 

### Additional information

Attention required to any existing GitHub guidelines involving content for different Windows versions.

---
[maintainer edit]
[Anyone](https://github.com/github/docs/issues/698#issuecomment-967507886) is welcome to open a PR documenting the information for Windows Credential Manager.

**Comment by felicitymay** [comment] 2020-10-22 11:50
Hi @casals - I've taken the liberty of updating the issue description to include a little more of the information from the original issue - it just means that people can see what this is about at a glance.

The writers at GitHub always start a content plan by thinking about who we're writing for, what they need to know, and what questions they might have. Then we plan the content to address those needs. We work from a template that reminds us what we need to think about. I've included the simplified template that we've recently started using to write content plans for open source contributors below. 

For this issue, the existing macOS topic is probably also a good resource for thinking about what needs to be in the new topic for Windows users, but there may be additional considerations for Windows users.

```
## Content plan

Summarize the issue, the impact on GitHub users, and the documentation changes we'll make to resolve the issue.

### Audience

Describe the audience for the change.

### Content to update

List the articles we'll update with relevant details on the change to make.

### Questions

If you have any questions after writing a plan, ask them here!
```

**Comment by casals** [comment] 2020-10-22 11:55
Thanks!

**Comment by lecoursen** [comment] 2021-11-12 20:36
Just noting here for clarity that you or anyone else is welcome to create a PR to add new article in the same category, "[Getting started with Git](https://docs.github.com/en/get-started/getting-started-with-git)" with this information. Thanks again @casals!

**Comment by ArkaprabhaChakraborty** [comment] 2022-10-07 19:31
Can I work on this too? I do need a headstart on what I should be doing.

**Comment by janiceilene** [comment] 2022-10-10 11:49
👋 @ArkaprabhaChakraborty the first steps for this issue are described in https://github.com/github/docs/issues/698#issuecomment-714439503. You can use the template to create a content plan and drop it as a new comment in this issue 💖 

I also just realized this was listed as a "good first issue" which isn't quite accurate, so I've removed that label 💛

**Comment by shejushejeer** [comment] 2023-06-21 17:28
> This issue is a partial breakdown from issue #429 (see [this comment](https://github.com/github/docs/issues/429#issuecomment-709217217)).
> 
> ### What article on docs.github.com is affected?
> 
> Currently there's a topic to help macOS users update their credentials: [Updating credentials from the macOS Keychain](https://docs.github.com/en/free-pro-team@latest/github/using-git/updating-credentials-from-the-macos-keychain) . The sub-issue here is the need for a Windows Credential Manager documentation page to complement this content.
> 
> ### What part(s) of the article would you like to see updated?
> 
> This requires a new article. 
> 
> ### Additional information
> 
> Attention required to any existing GitHub guidelines involving content for different Windows versions.
> 
> ---
> [maintainer edit]
> [Anyone](https://github.com/github/docs/issues/698#issuecomment-967507886) is welcome to open a PR documenting the information for Windows Credential Manager.
> 

Qut

**Comment by alexis-opolka** [comment] 2023-06-29 13:26
Hi @janiceilene,
Is this issue still open to contributions? If possible I'd like to work on it. ^-^

**Comment by cmwilson21** [comment] 2023-06-30 02:41
👋 @alexis-opolka - You, or anyone else, are welcome to work on this issue 💖

**Comment by alexis-opolka** [comment] 2023-07-01 14:16
After having thought a bit about it, here is my proposition of a content plan:

## Content plan

The issue is the lack of a documentation page on Windows Credential Manager while there's one for macOS, as pointed out by @casals.
I think it would be better to rename the [updating-credentials-from-the-macos-keychain](https://docs.github.com/en/get-started/getting-started-with-git/updating-credentials-from-the-macos-keychain) page to something more global such as `updating-credentials-from-your-keychain` with the new page including both Windows and macOS, even Linux if deemed appropriate.

### Audience

The audience would be beginners with Git on one of the OS cited above learning on how to update their credentials.

### Content to update

The [updating-credentials-from-the-macos-keychain](https://docs.github.com/en/get-started/getting-started-with-git/updating-credentials-from-the-macos-keychain) page should be updated with the choice of the OS like in [adding-a-new-ssh-key-to-your-github-account](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account).  
The current content should be placed under the macOS part and new steps should be created for windows and/or Linux.

### Questions

Will it be interesting to add some screenshots in both Windows and macOS sections as the audience, from what I understand, is beginners?

---

Please feel free to criticate my proposed content plan, I'd love to have any insightful feedback. ^-^

**Comment by alexis-opolka** [comment] 2023-07-12 11:33
Hi @cmwilson21,
Sorry for the ping but I'd like to know if someone had the time to look a bit more into this issue and read the content plan I'm proposing as I'm waiting to work on it since the `needs content strategy` is still assigned to this issue.  
Thanks in advance. ^-^

**Comment by alexis-opolka** [comment] 2023-08-13 14:47
Hi @cmwilson21👋🏼,
Are there any news regarding this issue? ^-^

**Comment by cmwilson21** [comment] 2023-08-21 15:49
@alexis-opolka Thank you for the ping! I'll get eyes on this 👀

**Comment by cmwilson21** [comment] 2023-08-30 19:34
@alexis-opolka I like the idea of consolidating the articles into one page and using something like our tool switcher to select the appropriate operating system. I hesitate with renaming it `updating-credentials-from-your-keychain` as the Windows version is Windows Credential Manager and doesn't use the word "keychain". So maybe even making it more generic like "Managing your credentials" makes it more flexible. 

To add articles based on operating systems, check out our Markdown and Liquid guide section on [operating system tags](https://docs.github.com/en/contributing/syntax-and-versioning-for-github-docs/using-markdown-and-liquid-in-github-docs#operating-system-tags).

Here's more information about [changing titles in the docs](https://docs.github.com/en/contributing/syntax-and-versioning-for-github-docs/changing-an-articles-title). 

As for the screenshots, I would hesitate to add them here because it's my understanding that we are referring to personal operating system screenshots as opposed to GitHub interface screenshots. We have less control and knowledge of updates when regarding operating system UI. Although I really appreciate your consideration for our beginner users, I think leaving screenshots out of this one would be the right call. You can find more about our criteria for including screenshots [here](https://docs.github.com/en/contributing/writing-for-github-docs/creating-screenshots#criteria-for-including-a-screenshot).

My apologies again for the delay, but I hope some of this information is helpful 💖

**Comment by alexis-opolka** [comment] 2023-09-01 19:09
Hi @cmwilson21👋🏼,

Thank you for those precious links, I'll be sure to read them. 😄 

I think "Managing your credentials" is the kind of title we need for this article because it will be generic enough to keep the users without much "technical" knowledge without losing the meaning of what the user is going to read on the page. 👍🏼 

I think you're indeed right about including screenshots that are not relevant to a GitHub product, while it may help beginners to visually see what to do, if the screenshots are not up to date they may do the countrary and perturb the beginners or that would mean an increase in work load to make sure to be up to date with each UI elements of other products.

I think I'll be able to work on a draft during the weekend, just after I sent my applications for internships abroad, would it be ok for me to ping you then? ^-^

**Comment by cmwilson21** [comment] 2023-09-01 19:30
@alexis-opolka You are exactly right about screenshots being more of a burden and increase in work in some cases. 👍 

I'll get a notification when your PR is opened in this repo, but you are welcome to ping me for visibility ✨

**Comment by mark-mxwl** [comment] 2024-01-18 23:41
Hi @cmwilson21 and @alexis-opolka! I've been looking deeper into this issue, and I wonder whether or not a new article is needed to resolve this. Both Git Credential Manager (included with Git for Windows) and GitHub CLI store credentials in Windows Credential Manager. There's really no need for the user to update these credentials manually. [Caching Your GitHub Credentials in Git](https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git?platform=windows) covers both options and also addresses how to delete outdated credentials cached in WCM, should they cause conflicts.

If you agree that the linked article satisfies the primary concerns here, I would recommend that this issue be marked as closed. Thanks! 🙂

**Comment by nguyenalex836** [comment] 2024-01-19 16:57
@mark-mxwl Thank you for raising this point! I am in agreement ✨  I'll go ahead and close this issue out, but we of course can reopen should a need arise in the future 💛

**Closed by nguyenalex836** 2024-01-19 16:57 UTC
Labels: help wanted, needs content strategy

**Comment by mark-mxwl** [comment] 2024-01-19 17:14
Thanks, @nguyenalex836! 🙂
