### ISSUE TITLE
Article assumes there are Report links on Issue comments

### ISSUE THREAD

**Issue by jidanni** [github/docs#35070] opened 2024-10-25 03:11 UTC
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/maintaining-your-safety-on-github/reporting-abuse-or-spam#reporting-a-comment

### What part(s) of the article would you like to see updated?

There are no "report comment" links on comments on issues. 

### Additional information

The article assumes that there are.

**Comment by nguyenalex836** [comment] 2024-10-25 15:51
Thank you for opening this issue, @jidanni! ✨ 

Just for clarification, you aren't seeing the "Report content" option after clicking the three dots in the upper right corner of a comment? What repositories are you attempting this in?

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/ea0b148f-9fe5-4d6f-8079-72802b313e52">

**Comment by jidanni** [comment] 2024-10-25 22:38
All I know is...

![Screenshot 2024-10-26 06 36 51](https://github.com/user-attachments/assets/55752f5d-3e55-4b53-97d2-7598c44e32a1)

See? No "report" choice!

**Comment by nguyenalex836** [comment] 2024-10-28 15:40
@jidanni Thanks for the screenshot! 

This may be an issue with your account, but we are unable to know for sure as our Docs team does not have the necessary tools to troubleshoot. However, pur wonderful [support team](https://support.github.com/request) is best equipped to determine what the root cause is ✨ Please reach out to them for assistance!

I'll go ahead and close this issue 💛

**Comment by jidanni** [comment] 2024-11-03 10:01
They said:

> Thanks for contacting GitHub Support!
>  
> Who can report content in issues or pull requests in a repository is controlled by your access and previous interactions with the repository - From [Reporting abuse or spam](https://docs.github.com/communities/maintaining-your-safety-on-github/reporting-abuse-or-spam#title-h1):
> Owners, collaborators, prior contributors, and people with write access can report issues, pull requests, discussions, and comments on issues, pull requests, discussions, and commits. Anyone can report apps in GitHub Marketplace.

So apparently the general case of users creating issues on unrelated projects is not covered. Thus your document needs to be revised.

**Comment by nguyenalex836** [comment] 2024-11-04 16:58
@jidanni Thanks for returning with that info! I'll get this up for review by our technical writing team 💛

**Comment by nguyenalex836** [comment] 2024-11-04 17:02
@jidanni Thanks for returning with that information! Do you have a suggestion regarding what update you would make to the doc? We'll be happy to review whatever you propose 💛

**Comment by nguyenalex836** [comment] 2024-11-04 17:10
@jidanni Thanks for returning with that information! Given the article our Support team pointed you toward, do you have any suggestions regarding what updates you would make to the doc? We'll be happy to review whatever you propose 💛

**Comment by jidanni** [comment] 2024-11-08 09:15
Actually my secret motive for posting here, is for GitHub Corporation to realize that anybody should be able to report a comment.

Just like how anybody can dial 911.

If you restrict reporting "privileges" to certain "classes of people", then well, "many fires may not end up getting reported to the fire department."

Yes, you might say
> Well, @jidanni, take that up with the GitHub Corporation. We're just the document team. Case closed.

But I'll have you know that I did, but was unsuccessful. So I hereby leave the issue in your laps. Sorry about that. Thanks.

**Comment by nguyenalex836** [comment] 2024-11-08 17:47
> But I'll have you know that I did, but was unsuccessful. So I hereby leave the issue in your laps. Sorry about that. Thanks.

No worries - we appreciate your willingness to voiced your feedback 💛

**Closed by nguyenalex836** 2024-11-08 17:47 UTC
Labels: content, communities, more-information-needed
