### ISSUE TITLE
GitHub Actions Runner Controller - actions.summerwind.net/v1alpha1 is not officially supported by GitHub

### ISSUE THREAD

**Issue by molson504x** [github/docs#27336] opened 2023-08-09 20:43 UTC
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/about-actions-runner-controller

### What part(s) of the article would you like to see updated?

In the "About Custom Resources" section, it lists the `actions.summerwind.net/v1alpha1` Kubernetes API resource definitions.  However in [actions/actions-runner-controller discussion - Autoscaling Runner Scale Sets mode is now generally available](https://github.com/actions/actions-runner-controller/discussions/2775) it indicates that the `actions.summerwind.net/v1alpha1` is **community-supported** and is not officially supported by GitHub.  If that is the case, the official docs should either omit those CRDs or should probably note that they are not officially supported by GitHub.

**Comment by cmwilson21** [comment] 2023-08-10 13:44
@molson504x Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by Shama13676Q** [comment] 2023-08-12 13:15
2

**Comment by hubwriter** [comment] 2023-08-14 14:37
Hi @molson504x - Thanks for raising this docs issue. I have asked for an ARC subject matter expert to consider your suggestion.

**Comment by Link-** [comment] 2023-08-17 09:56
Hey @molson504x - thank you for your contribution. The docs currently have no mention of the legacy modes of ARC by design and we'd like to keep it that way for now. As part of the gha-runner-scale-set-0.5.0 release (to be published before end of August) we have made changes to the repository README that will make the distinction very clear: https://github.com/actions/actions-runner-controller/pull/2779

On top of that, I drafted this announcement a while back to clarify everything related to what is supported by GitHub and what's owned by the community: https://github.com/actions/actions-runner-controller/discussions/2775

**Comment by hubwriter** [comment] 2023-08-22 15:44
Closing this out.

**Closed by hubwriter** 2023-08-22 15:44 UTC
Labels: content, actions, waiting for review
