### ISSUE TITLE
Repeat headers and content in doc 

### ISSUE THREAD

**Issue by HananoshikaYomaru** [github/docs#14493] opened 2022-01-23 05:13 UTC
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/getting-started-with-git/associating-text-editors-with-git

### What part(s) of the article would you like to see updated?

repetitive headers and sections when first render the page. should be a bug. The default option should be mac and there should be only 4 headers.

### Additional information

![CleanShot 2022-01-23 at 13 09 52](https://user-images.githubusercontent.com/43137033/150665856-e7712908-1b3a-48b7-8da5-030e65063d86.png)

should be ⬇️

![CleanShot 2022-01-23 at 13 12 29](https://user-images.githubusercontent.com/43137033/150665907-43f27451-6314-4b6e-b8d5-7eeb94f287a6.png)

**Comment by ramyaparimi** [comment] 2022-01-24 15:50
@HananoshikaYomaru 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by felicitymay** [comment] 2022-01-26 17:13
@HananoshikaYomaru - thanks for reporting this problem.

When you first open this article, it sounds as if you see all the headings in the sidebar. Not just the ones for Mac. I'm interested to hear about this but can't reproduce it. I'm also on Mac and see the four expected headings.

Can you tell us which browser version and operating system you are using?

**Comment by HananoshikaYomaru** [comment] 2022-01-30 04:16
I am using microsoft edge, Version 97.0.1072.76 (Official build) (x86_64). 

https://user-images.githubusercontent.com/43137033/151686385-d7319fc1-82d4-4e1b-8a32-a2da6610ca79.mp4

**Comment by felicitymay** [comment] 2022-01-31 08:47
@HananoshikaYomaru - thank you for the animated gif and clear details of your browser version. That's really helpful.

I'm able to reproduce the behavior you saw in both Windows and on a Mac. As far as I can tell, all works well until you choose a different platform from the one that you are using, then you get the header and content duplication you describe.

Thanks for looking to see if you could fix the problem, but I agree with you that this isn't a problem with the markdown file. I'm going to open an internal issue with the great details you've provided, for the docs engineering team to look at. Since this cannot be fixed here, I'm going to close this issue.

**Closed by felicitymay** 2022-01-31 08:47 UTC
Labels: content, waiting for review

**Comment by felicitymay** [comment] 2022-02-07 11:09
@HananoshikaYomaru - our site engineers think that they have fixed this problem. Thank you so much for reporting it 💖
