### ISSUE TITLE
Discussion formats aren't actually documented

### ISSUE THREAD

**Issue by jsoref** [github/docs#31056] opened 2024-01-11 15:09 UTC
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-categories-for-discussions
https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions#about-categories-and-formats-for-discussions

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-categories-for-discussions
Says:
> Edit the emoji, title, description, and discussion format for the category. For more information about discussion formats, see "[About discussions](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions#about-categories-and-formats-for-discussions)."

https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions#about-categories-and-formats-for-discussions

There is no *section* in this article that talks about Formats. There should be.

Instead, the page has this very long form prose which does *not* help anyone figure out anything and doesn't explain the risks of using the Announcement format, nor does it make clear what formats are. Here's the unhelpful prose:

> You can categorize discussions to help community members begin conversations in the right place, and to help community members find related discussions. All discussions must be created in a category. For repository discussions, people with maintain or admin permissions to the repository define the categories for discussions in that repository. For organization discussions, people with maintain or admin permissions to the source repository define the categories for discussions in that organization. Each category has a format: open-ended discussion, question and answer, or announcement. Each repository or organization can have up to 25 categories.
>
> For discussions with a question/answer format, an individual comment within the discussion can be marked as the discussion's answer. GitHub will automatically recognize community members who contribute the most comments marked as answers to discussions with a question/answer format.
>
> Maintainers can use categories with the announcement format to share information, releases, or events. To keep discussions in these categories focused on important updates, only people with maintain or admin permissions can create new discussions, but anyone can comment and reply.

### Additional information

This comes up because there is a gap explaining that you can't transfer announcements across repositories.

**Comment by KirinRyu** [comment] 2024-01-13 04:10
Thank you @jsoref for opening this! 😊

**Comment by nguyenalex836** [comment] 2024-01-22 17:06
@jsoref Thank you for bringing this to our attention! ✨ The team discussed a few different approaches we could take to handle this information gap with respect to Formats, and we found the most efficient solution would be to take the sentence

> Each category has a format: open-ended discussion, question and answer, or announcement. Each repository or organization can have up to 25 categories.

and add it to "Editing a category" procedural. Thank you again for raising this flag on this 💛

**Comment by nguyenalex836** [comment] 2024-01-22 17:13
Internal: Discussed in [Slack](https://github.slack.com/archives/C044769JDV5/p1705943334269989?thread_ts=1705942620.345339&cid=C044769JDV5)

**Comment by jsoref** [comment] 2024-01-22 17:25
It'd need to be in both `Creating a category` and `Editing a category`:

1. On GitHub.com, navigate to the main page of the repository or organization where you want to create a category.
2. Under your repository or organization name, click  Discussions.
    (Screenshot of the tabs in a GitHub repository. The "Discussions" option is outlined in dark orange.)
3. In the left sidebar, to the right of "Categories", click .
    (Screenshot of the "Categories" menu on the Discussions page. The pencil icon for editing categories is highlighted with an orange outline.)
4. Click New category.
    (Screenshot of the "Manage discussion categories" page.  A button, labeled "New category", is highlighted with an orange outline.)
5. Edit the emoji, title, description, and discussion format for the category. For more information about discussion formats, see "[About discussions](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions#about-categories-and-formats-for-discussions)."
6. Optionally, add the category to a section. A category can only belong to one section at a time. For information on how to create a section, see "[Creating a section](https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-categories-for-discussions#creating-a-section)."
    (Screenshot of part of the "Create category" page, showing the option to add a category to a section.)
7. Click Create.

----

You can edit a category to change the category's emoji, title, description, and discussion format.

1. On GitHub.com, navigate to the main page of the repository or organization where you want to edit a category.
2. Under your repository or organization name, click  Discussions.
    (Screenshot of the tabs in a GitHub repository. The "Discussions" option is outlined in dark orange.)
3. In the left sidebar, to the right of "Categories", click .
    (Screenshot of the "Categories" menu on the Discussions page. The pencil icon for editing categories is highlighted with an orange outline.)
4. To the right of a category in the list, click .
5. Edit the emoji, title, description, and discussion format for the category. For more information about discussion formats, see "[About discussions](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions)."
6. Optionally, add the category to a section. A category can only belong to one section at a time. For information on how to create a section, see "[Creating a section](https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-categories-for-discussions#creating-a-section)."
    (Screenshot of part of the "Create category" page, showing the option to add a category to a section.)
7. Click Save changes.

The current content appears to come from:
https://github.com/github/docs/blob/508943112c013fbbb145df8ef2a182a09fdcd742/data/reusables/discussions/edit-category-details.md?plain=1

It sounds like the team is suggesting editing that reusable element and adjusting the text as described... that's doable.

The downside is that it's hard for someone to link to a thing that just talks about discussion formats as opposed to pages specifically for created/editing categories.

**Comment by jsoref** [comment] 2024-01-22 18:17
Also note that one of the reasons I'm looking at this is that the `announcement` format is apparently _extra special_ in that you can't move a discussion in that category to another repository **period**.

It'd be helpful to be able to hang this note in the documentation, and it doesn't really make sense to hang it in the create/edit page...

**Comment by HOLYGHOST1111** [comment] 2024-01-22 18:53
- [ ] 
Duplicate of #

**Comment by nguyenalex836** [comment] 2024-01-22 23:26
@jsoref 

> The downside is that it's hard for someone to link to a thing that just talks about discussion formats as opposed to pages specifically for created/editing categories.

> announcement format is apparently extra special in that you can't move a discussion in that category to another repository period.

Great points! I'll bring these up w/ the team as we continuing working through this 👍

**Comment by jsoref** [comment] 2024-01-25 02:38
This is needed for:
https://github.com/github/docs/issues/31057

**Comment by sophietheking** [comment] 2024-01-31 10:31
I merged a PR to update the step, which now explains formats and that announcements cannot be transferred. Closing this! ✨

**Closed by sophietheking** 2024-01-31 10:31 UTC
Labels: content, waiting for review, SME reviewed

**Comment by jsoref** [comment] 2024-02-08 03:57
I can't find it... Can you provide a link?

**Comment by nguyenalex836** [comment] 2024-02-08 17:28
@jsoref Howdy! 👋 @sophietheking's PR was merged in a different repo, but the changes were also made in this repo via an automated repo sync

**Comment by jsoref** [comment] 2024-02-08 17:29
I get that. But I can't find the text in this repo.

**Comment by jsoref** [comment] 2024-02-08 17:42
To be clear: I'm looking for a link in this repository to the new text or a link to docs.github.com w/ the new text.

**Comment by nguyenalex836** [comment] 2024-02-08 17:48
@jsoref Gotcha 👍 I believe [this](https://github.com/github/docs/commit/c211dc56a0c340c6195de0c26fbba976472318e0) might be what you're looking for

**Comment by jsoref** [comment] 2024-02-08 18:30
Thanks, that covers half the problem.

For reference, the new text can be seen here:
https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-categories-for-discussions#creating-a-category

It isn't available here:
https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-discussions#transferring-a-discussion

**Comment by nguyenalex836** [comment] 2024-02-08 19:38
@jsoref Thanks for pointing that out! Would you be willing to open a PR to update this? I see there is currently a sentence that reads 

> You can only transfer discussions between repositories owned by the same user or organization account.

This could be updated to read

> You can only transfer discussions between repositories owned by the same user or organization account, and only if they are not announcements (see "[Creating a category](https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-categories-for-discussions#creating-a-category)").

Going to loop in @sophietheking as well, just to see if she has any thoughts on the past few comments 💛

**Comment by jsoref** [comment] 2024-02-08 20:09
I opened https://github.com/github/docs/pull/31540. Note that I do not like the proposal and would much prefer the text to be converted from a paragraph to a list, but documenting is better than not documenting.

**Comment by nguyenalex836** [comment] 2024-02-08 21:32
We appreciate the transparency and flexibility, @jsoref 💛 Thank you for linking the PR! We can wait til @sophietheking has had a chance to chime in before we action further
