### ISSUE TITLE
Put Dependabot in gallery on landing page and in the sidebar

### ISSUE THREAD

**Issue by HonkingGoose** [github/docs#5953] opened 2021-05-02 11:42 UTC
### What is the current behavior?

It's hard to find the documentation entrypoint for Dependabot.

This is probably what happens to newcomers to the GitHub docs:

1. Go to the main landing page: https://docs.github.com/en
1. Search on landing page for "Dependabot" in browser search (<kbd>CTRL + F</kbd>), no hits.
1. Use docs-native search with string "Dependabot", get no hits about enabling Dependabot.

### What changes are you suggesting?

I think it would be great to have links/text that references Dependabot on the main landing page of the docs.

- Create new item in sidebar called "Dependabot".
- Create new item in "Explore by product" gallery on the homepage for the GitHub docs, called "Dependabot".

This way users can find the docs for Dependabot by viewing the sidebar, looking in the "gallery" on the homepage, or by searching in their browser for the string "Dependabot" and find the sidebar/gallery items.

### Additional information

Inspired by the confusion a user had with finding Dependabot docs in issue: #5946.

**Comment by chiedo** [comment] 2021-05-03 14:15
cc @emilyistoofunky

**Comment by lee-dohm** [comment] 2021-05-03 18:55
Thanks @HonkingGoose for your detailed feedback! Having the steps to reproduce your experience was especially helpful in understanding the problem you’re describing.

I also want to say that [going the extra mile to help someone out](https://github.com/iHildy/next-tailwind-template/pull/1) when they were in need is very much appreciated. This kind of helpful and cooperative attitude is what attracted me, personally, to open source in the first place and keeps me excited and hopeful about efforts like open sourcing the GitHub documentation.

Upon reviewing this with the team, we feel the real failure here is the inability to search for the information that was needed. The search experience in the GitHub Docs is not especially useful at times. This is something that we have targeted for improvement and are currently investigating how best to achieve those gains. Because we’re still scouting out alternatives with their various pros and cons, we can’t give a timeline for when we’ll be able to roll out changes, however be assured that this is a pain point that we experience as well and want to see fixed. Because this is a search issue and not something that we would change the gallery or sidebar for, we’re going to close this issue.

Thanks again for contributing to the GitHub Docs and your interest in seeing them improved! We truly appreciate your ongoing efforts and eagerness to help people 💖

**Closed by lee-dohm** 2021-05-03 18:55 UTC
Labels: triage

**Comment by HonkingGoose** [comment] 2021-05-03 19:26
> I also want to say that [going the extra mile to help someone out](https://github.com/iHildy/next-tailwind-template/pull/1) when they were in need is very much appreciated. This kind of helpful and cooperative attitude is what attracted me, personally, to open source in the first place and keeps me excited and hopeful about efforts like open sourcing the GitHub documentation.

Thank you very much for the compliment! 😄 🥳 

> Because this is a search issue and not something that we would change the gallery or sidebar for, we’re going to close this issue.

That's ok, at least now it on the radar. Thanks for discussing my idea with the team, and for your helpful explanation of the reason for closing the issue!

> Thanks again for contributing to the GitHub Docs and your interest in seeing them improved! We truly appreciate your ongoing efforts and eagerness to help people 💖

🥳 ❤️
