### ISSUE TITLE
Improve documentation on variables and reusables

### ISSUE THREAD

**Issue by casals** [github/docs#210] opened 2020-10-07 22:53 UTC
### What article on docs.github.com is affected?

The specific `README.md` files for both variables and reusables; `CONTRIBUTING.md`

### What part(s) of the article would you like to see updated?

As they are now, these files are a little bit dry - it's not something that's intuitively usable by first-time contributors. I suggest both of these files could be updated to look like the one for [liquid tabs](https://github.com/github/docs/blob/main/lib/liquid-tags/README.md), with references, usage examples, etc. 

Also - adding a brief section on each of these (liquid tabs, variables, reusables, etc) would be extremely helpful.

## Content design plan

- [ ] Open for an OS contributor: For specific `README.md` files, I think they should be as complete as possible: definitions, examples, everything that a content contributor could learn about what's being referenced (code intrincacies = negative scope).
- [ ] @janiceilene will make these changes: As for `CONTRIBUTING.md`: IMHO it should be a complete quick start. Let's take, for instance, the last 24h: I was learning about variables, reusables, and callout tags as the PRs were reviewed. I mean, the technical detailes are there if I follow the md links, but the text doesn't give me any reasons to do so. And even if I do it, there's no clear benefit for the newcoming contributor - it reads and feels like technical documentation (which is technically not wrong, but not necessarily helpful to a newcomer as such). 
  - [ ] Structure the CONTRIBUTING.md file more like a quick start guide - "welcome, here's the basic stuff you need to know, here's why you need to know it, here's where you can learn more about each of them" - paced, with simple examples. Perhaps something like [this](https://github.com/MovingBlocks/Terasology/wiki/How-to-Work-on-a-PR-Efficiently).

**Comment by janiceilene** [comment] 2020-10-08 18:54
@casals Those two docs could definitely be better! Any thoughts about what kinds of information you think would be helpful there?

**Comment by casals** [comment] 2020-10-08 19:10
Sure - for specific `README.md` files, I think they should be as complete as possible: definitions, examples, everything that a content contributor could learn about what's being referenced (code intrincacies = negative scope).

As for `CONTRIBUTING.md`: IMHO it should be a complete quick start. Let's take, for instance, the last 24h: I was learning about variables, reusables, and callout tags as the PRs were reviewed. I mean, the technical detailes are there if I follow the md links, but the text doesn't give me any reasons to do so. And even if I do it, there's no clear benefit for the newcoming contributor - it reads and feels like technical documentation (which is technically not wrong, but not necessarily helpful to a newcomer as such). 

IMHO this particular document should be structure more like a quick start guide - "welcome, here's the basic stuff you need to know, here's why you need to know it, here's where you can learn more about each of them" - paced, with simple examples. Perhaps something like [this](https://github.com/MovingBlocks/Terasology/wiki/How-to-Work-on-a-PR-Efficiently).

**Comment by asadovtair** [comment] 2020-10-12 14:04
#440 #442 #441
Duplicate of #443

**Comment by asadovtair** [comment] 2020-10-12 14:47
_Sent from my Mi MIX 3 5G using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_asadovtair@gmail.com

**Comment by janiceilene** [comment] 2020-10-12 23:33
Yeah, I agree the readmes for the variables and reusables could benefit from all the things you described! If someone wants to tackle that information. That'd be awesome ⚡ If not, it's now here in an issue and we'll get back to it 😅 

The plan on the contributing.md right now is to mostly leave it as is. After Hacktoberfest 🎃 I think it'd benefit from an update and maybe a supplementary document to really walk new contributors through everything, step by step. If you're interested, I'd love to get your reviews on those when they happen!

**Comment by casals** [comment] 2020-10-12 23:39
Actually @janiceilene I was just waiting for some input on this. So - should I wait until Hacktoberfest? I wouldn't mind giving it a go this week - writing content is relaxing. :)

**Comment by janiceilene** [comment] 2020-10-12 23:55
If you want to work on the variables and reusables content, that'd be great 😻 Feel free to start a PR and let me know if you have any questions or need any clarification.

Major changes to the contributing.md are what I'd like to wait until November to start.

**Comment by saduqur80** [comment] 2021-01-24 10:01
Diff

**Comment by saduqur80** [comment] 2021-01-24 10:02
Git diff

**Comment by ramyaparimi** [comment] 2021-09-23 13:26
Recent update to contributing guides addresses all the points mention in this issue ✨ 🐬 Closing the issue!

**Closed by ramyaparimi** 2021-09-23 13:26 UTC
Labels: help wanted, contributing docs
