### ISSUE TITLE
The manage multiple accounts docs aren't accurate on what happens

### ISSUE THREAD

**Issue by jessehouwing** [github/docs#24559] opened 2023-03-20 19:56 UTC
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-personal-account/managing-multiple-accounts.md

### What changes are you suggesting?

This doc mentions that for each local folder the credential manager will ask for an access token, but I don't think this is true. For each clone URL it will ask for a credential, but if you clone the same repo twice on the same machine, it shouldn't care if the clone was made into 2 separate folders. 

### Additional information

The `useHttpPath` property uses the clone url to store the access token. It doesn't care about the local working folder.

**Comment by ANKIT-desigh** [comment] 2023-03-21 06:07
there may be possible that the user may have locked or change the passsword

**Comment by cmwilson21** [comment] 2023-03-21 20:05
@jessehouwing Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by dawncharles85** [comment] 2023-03-26 06:55
Duplicate of #

**Comment by Ibrahim7388** [comment] 2023-04-06 20:21
0xddBa66C1eBA873e26Ac0215Ca44892a07d83aDF5

**Comment by Saeidnasiri** [comment] 2023-04-15 21:18
58186345

**Comment by Saeidnasiri** [comment] 2023-04-15 21:19
Hello job

**Comment by isaacmbrown** [comment] 2023-04-26 14:49
Hi @jessehouwing, thanks for submitting this issue!

I'm just working out exactly which steps you'd be looking to update here.

Are the following steps the ones that are looking inaccurate?

Step 4:

> To configure Git to cache credentials for each local directory where you clone a repository, enter the following command

Step 6:

> Git will cache the personal access token for the directory you're in

And you would suggest we update to something like the following?

Step 4:

> To configure Git to cache credentials for each repository you clone, enter the following command

Step 6:

> Git will cache the personal access token for the repository you're in

If so, I'd expect this isn't causing too much confusion for most users, but if you would like to open a PR to fix this, then go ahead 🙂

**Comment by jessehouwing** [comment] 2023-04-26 15:30
I also don't think it would cause confusion, but it's inaccurate. Ideally the docs would explain clearly what the effect is, cause even the update isn't entirely accurate.

The reason is that the logic isn't all that intuitive, as it's based on the remote's url.

> * Step 4: To configure Git to cache credentials for each GitHub repository by its clone url, enter the following command.
> * Step 6: Git will cache the personal access token for the repository using the clone url as key.

Cloning the same repo twice on the same machine won't cause the credential to be prompted, it has that  available in the credential cache. If you replace the contents of a repo with that of another, the credentials won't work. If you change the remote url of the repo. the credentials will no longer work. But if you change the credentials of ANOTHER repo on disk to the remote of a cached repo, the credentials WILL be reused. Cause, the repo on disk has nothing to do with how the credentials are retrieved.

**Closed** 2023-04-27 11:34 UTC
Labels: content, waiting for review, account-and-profile
