### ISSUE TITLE
Unclear if transfer repo and associated redirect applies to releases

### ISSUE THREAD

**Issue by RoxaBee** [github/docs#1941] opened 2020-12-09 20:04 UTC
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository

### What part(s) of the article would you like to see updated?

Include something on what happens to releases when a repo is transferred from account/organization to another. Will the releases be transferred along with issues, in-flight pr, etc. Also will the redirect apply to releases as well?

**Comment by janiceilene** [comment] 2020-12-09 21:45
Ooh, that's an interesting one @RoxaBee thanks for opening an issue! I'll need to ask around and find out the answer. I'll report back when I figure it out 👀

**Comment by janiceilene** [comment] 2020-12-09 22:23
@RoxaBee I just checked in with engineering and they confirmed that releases are transferred with everything else! Since almost everything is included in a transfer, I think we'll keep documenting the exceptions instead of explicitly calling out releases as being included. I'm going to close this out now, thanks for contributing! 💖

**Closed by janiceilene** 2020-12-09 22:23 UTC
Labels: triage

**Comment by RoxaBee** [comment] 2020-12-09 22:31
Thanks @janiceilene !

**Comment by glennwester** [comment] 2020-12-09 22:36
Thanks Roxana! @janiceilene Noting that we could also add some language about what happens to GitHub Packages in the repo ownership transfer to our doc 👍

**Comment by janiceilene** [comment] 2020-12-09 23:04
@glennwester Could you open an issue in [docs-content](https://github.com/github/docs-content) outlining what happens and we can figure out how to best incorporate that into the docs? Thank you!

**Comment by RoxaBee** [comment] 2020-12-09 23:18
Hi @janiceilene maybe easier to just reopen the issue? @glennwester learned that the packages in the GitHub Package Registry are transferred along with the repository and are subsequently only available at the new repository location. There is no forward so not quite the same and maybe should be called out.

**Comment by janiceilene** [comment] 2020-12-10 16:55
Thanks @RoxaBee! I think we're going to look at updating the package docs internally with some other work we're doing ⚡
