### ISSUE TITLE
Instruction list being repeated thrice.

### ISSUE THREAD

**Issue by Anmol-Singh-Jaggi** [github/docs#1525] opened 2020-11-21 13:40 UTC
On [this page](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account), the list is being repeated thrice.
Attaching a printed version of the html page for reference.
[github-adding-ssh.pdf](https://github.com/github/docs/files/5577708/github-adding-ssh.pdf)

Couldn't figure out how to fix it.

**Comment by janiceilene** [comment] 2020-11-23 15:49
Thanks for opening an issue @Anmol-Singh-Jaggi! Next time, please fill out the [issue template](https://github.com/github/docs/blob/main/.github/ISSUE_TEMPLATE/improve-existing-docs.md) to help us better understand the problem 💛 

I'm not seeing what's causing the repeat 🤔 I assumed it was a problem with the [OS tags](https://github.com/github/docs/blob/main/contributing/content-markup-reference.md#operating-system-tags), but I'm not seeing it after a quick scan.

Anyone is welcome to pick this up, troubleshoot, and open a PR to fix the problem!

**Comment by janiceilene** [comment] 2020-11-23 20:21
There was an internal PR that was causing `<li>` elements to break. The PR was reverted and this article looks right to me now, so I'm going to close this out 🎉 

Feel free to re-open if the issue isn't resolved or if I misunderstood.

**Closed by janiceilene** 2020-11-23 20:21 UTC
Labels: content, core, help wanted

**Comment by farukrana** [comment] 2020-12-08 05:36
all errors issues solved
