### ISSUE TITLE
octokit page missing content

### ISSUE THREAD

**Issue by jeffmcaffer** [github/docs#5736] opened 2021-04-26 21:34 UTC
### What article on docs.github.com is affected?
https://github.com/github/docs/blob/main/content/rest/overview/libraries.md

### What part(s) of the article would you like to see updated?

Seems that the most important part of that page is missing, the information about Octokit. Looking at [the source](https://github.com/github/docs/blob/main/content/rest/overview/libraries.md) for the page there is a section (#octokit-comes-in-many-flavors) but it has recently stopped showing up in the rendered view of the docs

**Comment by StarTrooper08** [comment] 2021-04-26 22:10
Hey , can I work on this issue?

**Comment by ajs256** [comment] 2021-04-26 22:26
Looks like the section is rendered as HTML:
```html

<div class="jumbotron libraries-jumbotron">
  <img src="/assets/images/gundamcat.png" class="gundamcat" alt="The Gundamcat" />
  <h1>Octokit comes in many flavors</h1>
  <p class="lead">Use the official Octokit library, or choose between any of the available third party libraries.</p>
  <div class="octokit-links"><br/>
     <div class="octokit-language"> <span>Ruby → </span><a href="https://github.com/octokit/octokit.rb">octokit.rb</a></div><br/>
     <div class="octokit-language"><span>.NET → </span> <a href="https://github.com/octokit/octokit.net">octokit.net</a></div><br/>
     <div class="octokit-language"><span>JavaScript → </span> <a href="https://github.com/octokit/rest.js">octokit/rest.js</a></div><br/>
  </div>
</div>
```
but the Docs renderer doesn't like it. This could just be reproduced as Markdown:
```markdown
![The Gundamcat](/assets/images/gundamcat.png)
# Octokit comes in many flavors
Use the official Octokit library, or choose between any of the available third party libraries.
* Ruby → [octokit.rb](https://github.com/octokit/octokit.rb)
* .NET → [octokit.net](https://github.com/octokit/octokit.net)
* JavaScript → [octokit.js](https://github.com/octokit/rest.js)
```
but there might be something special about the classes. Someone who knows the site's CSS could advise here.

**Comment by janiceilene** [comment] 2021-04-28 22:02
@github/docs-engineering Could someone 👀 this one and let us know if this is a content change or an engineering one?

**Comment by mikesurowiec** [comment] 2021-04-29 20:53
@janiceilene It looks like it's rendering now (unless I'm misunderstanding something). [link](https://docs.github.com/en/rest/overview/libraries) 👇 

![Screen Shot 2021-04-29 at 1 48 55 PM](https://user-images.githubusercontent.com/821435/116616525-a6906e00-a8f1-11eb-9794-9605fd8d95f4.png)

**Comment by janiceilene** [comment] 2021-04-30 23:00
Maybe it was just a weird caching bug! I'll close this out now, but let us know if we're missing something 💛

**Closed by janiceilene** 2021-04-30 23:00 UTC
Labels: content, triage
