### ISSUE TITLE
"About Code Owners" contradicts itself

### ISSUE THREAD

**Issue by Efruit** [github/docs#13845] opened 2022-01-09 03:40 UTC
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

### What part(s) of the article would you like to see updated?

Information in the first paragraph regarding permissions required to be a code owner conflicts with the **CODEOWNERS Syntax** section.

## Intro Paragraph
> __**The people you choose as code owners must have write permissions for the repository.**__ When the code owner is a team, that team must be visible and it must have write permissions, even if all the individual members of the team already have write permissions directly, through organization membership, or through another team membership.

## CODEOWNERS Syntax
> A CODEOWNERS file uses a pattern that follows most of the same rules used in gitignore files, with some exceptions. The pattern is followed by one or more GitHub usernames or team names using the standard @username or @org/team-name format. __**Users must have read access to the repository**__ and teams must have explicit write access, even if the team's members already have access. You can also refer to a user by an email address that has been added to their account on GitHub.com, for example user@example.com.

**Comment by ramyaparimi** [comment] 2022-01-10 13:22
@Efruit 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by Katuni1** [comment] 2022-01-12 18:41
Hi

**Comment by lecoursen** [comment] 2022-02-01 21:21
Thanks @Efruit, I just checked in with a support engineer who confirmed that only read access is required for users, while teams need write. You or anyone else is welcome to open a PR fixing that first quote!

**Comment by gubasza** [comment] 2022-02-04 10:20
[The Galaxy S22 is almost here – reserve now to save!](https://shop-links.co/cgw5Yaf3fFw)[](https://www.xda-developers.com/)[](https://twitter.com/xdadevelopers)[](https://www.facebook.com/xda.developers)[](https://www.youtube.com/user/xdadevelopers?sub_confirmation=1)[](https://discord.gg/e4v8qtkcBw)[](https://t.me/xdadevelopershub)[](https://www.xda-developers.com/feed)
XDA Developers
NEWS
FORUMS
DEVICES
TOPICS
BEST POSTS
close
Search
FORUMS
Register for Forums
Set up a new account on the XDA Developers Forums

Login to Forums
Sign in to the XDA Developers Forums

XDA’S APPS
Nav Gestures
Add swipe gestures to any Android, no root

One handed mode
Make your phone easier to use with one hand, no root

XDA Forum App
The best way to access XDA on your phone

Hyperion Launcher
A sweet, feature-filled launcher with a beautiful UX.

SITES WE LIKE
Swappa
XDA’s official marketplace for buying and selling tech

Pocketnow
Premium videos

SOCIAL
RESOURCES
[Subscribe to our Newsletter](https://www.xda-developers.com/newsletter-signup/)
[Contact](https://www.xda-developers.com/the-team/)
[About](https://www.xda-developers.com/about/)
[TIP US](https://www.xda-developers.com/tip-us/)
[Windows 11](https://www.xda-developers.com/windows-11/)
[Galaxy Fold 3](https://www.xda-developers.com/samsung-galaxy-z-fold-3/)
[5G](https://www.xda-developers.com/5g/)
[Galaxy Z Flip 3](https://www.xda-developers.com/samsung-galaxy-z-flip-3/)
[Android 12](https://www.xda-developers.com/android-12/)
[Galaxy S21](https://www.xda-developers.com/samsung-galaxy-s21/)
[OnePlus 9](https://www.xda-developers.com/oneplus-9/)
[Pixel 6](https://www.xda-developers.com/tag/google-pixel-6/)[](https://www.xda-developers.com/files/2021/09/PR-XPan_BW_02_Horizontal.jpg)
We are reader supported. External links may earn us a commission.
OnePlus 9’s latest OxygenOS update brings many camera improvements and Hasselblad XPan mode
 [September 17, 2021 8:00am](https://www.xda-developers.com/2021/09/)[Comment](https://www.xda-developers.com/oneplus-9-oxygenos-update-hasselblad-xpan-mode/#comment)[Kishan Vyas](https://www.xda-developers.com/author/kristinspradlin/)
[OnePlus 9](https://www.xda-developers.com/oneplus-9)’s latest OxygenOS update brings many camera improvements and Hasselblad XPan mode
For the OnePlus 9 series, OnePlus partnered up with the Swedish camera maker Hasselblad. This partnership did pay off as both the OnePlus 9 and [OnePlus 9 Pro](https://www.xda-developers.com/oneplus-9-pro-review/) finally delivered a flagship-level camera performance that OnePlus fans have been asking for many years. Since its launch, OnePlus has continued to tweak and improve the camera performance of the OnePlus 9 series with various software updates. With the latest [OxygenOS](https://www.xda-developers.com/tag/oxygenos/) update, OnePlus is going a step further.

[OnePlus finally gets the camera right on the OnePlus 9](https://www.xda-developers.com/oneplus-9-camera-review/)

OnePlus has just announced a new OxygenOS update for the OnePlus 9 and OnePlus 9 Pro which, among other camera improvements, adds a brand new camera mode: XPan Mode. XPan Mode, developed in close collaboration with Hasselblad, tries to mimic the camera experience of the [Hasselblad XPan camera](https://www.hasselblad.com/inspiration/history/xpan/)[](https://www.xda-developers.com/files/2021/09/PR-XPan_BW_02_Horizontal.jpg)[](https://www.xda-developers.com/files/2021/09/PR-XPan_Color_03_Horizontal.jpg)[](https://www.xda-developers.com/files/2021/09/PR-XPan_Color_06_Horizontal.jpg)[](https://www.xda-developers.com/files/2021/09/PR-XPan_Color_04_Horizontal.jpg)[](http://www.facebook.com/sharer.php?u=https%3A%2F%2Fwww.xda-developers.com%2Foneplus-9-oxygenos-update-hasselblad-xpan-mode%2F&t=OnePlus%209%E2%80%99s%20latest%20OxygenOS%20update%20brings%20many%20camera%20improvements%20and%20Hasselblad%20XPan%20mode)[](http://twitter.com/share?text=OnePlus%209%E2%80%99s%20latest%20OxygenOS%20update%20brings%20many%20camera%20improvements%20and%20Hasselblad%20XPan%20mode&url=https%3A%2F%2Fwww.xda-developers.com%2Foneplus-9-oxygenos-update-hasselblad-xpan-mode%2F&via=xdadevelopers)[](http://www.reddit.com/submit?url=https%3A%2F%2Fwww.xda-developers.com%2Foneplus-9-oxygenos-update-hasselblad-xpan-mode%2F&title=OnePlus%209%E2%80%99s%20latest%20OxygenOS%20update%20brings%20many%20camera%20improvements%20and%20Hasselblad%20XPan%20mode)[](https://news.ycombinator.com/submitlink?u=https%3A%2F%2Fwww.xda-developers.com%2Foneplus-9-oxygenos-update-hasselblad-xpan-mode%2F&t=OnePlus%209%E2%80%99s%20latest%20OxygenOS%20update%20brings%20many%20camera%20improvements%20and%20Hasselblad%20XPan%20mode)[](http://www.linkedin.com/shareArticle?mini=true&url=https%3A%2F%2Fwww.xda-developers.com%2Foneplus-9-oxygenos-update-hasselblad-xpan-mode%2F&title=OnePlus%209%E2%80%99s%20latest%20OxygenOS%20update%20brings%20many%20camera%20improvements%20and%20Hasselblad%20XPan%20mode) by allowing users to shoot panoramic images in a 65:24 format.

Photos taken with XPan Mode have an aspect ratio of 65:24 — similar to the original Hasselblad xPan camera. The camera mode outputs 20MP images, cropped from the 48MP sensor and 50MP ultra-wide sensor. [OnePlus](https://www.xda-developers.com/tag/oneplus/) notes that images are cropped from the respective camera’s native resolution — 48MP and 50MP — rather than the pixel-binned 12MP mode.

A black and white photo showing a man with umbrella
A photo shot with OnePlus9's XPan Mode showing a bridge and tall buildings
A photo shot with OnePlus9's XPan Mode depicting a person gazing at river with an open sky and buildings shown in the backdrop
A photo shot with OnePlus9's XPan Mode showing a person on the escalator

Xpan Mode offers two film simulation profiles, a color mode, which offers a rich and realistic color profile, and a classic black and white profile that mimics the tone and style of a classic black and white film used in XPan cameras.

“Working with Hasselblad on XPan Mode has helped us recreate their legendary experience of viewing your photographs in a 65:24 format before shooting a wide, panoramic image in 30mm and 45mm. Using XPan Mode on the [OnePlus 9](https://www.xda-developers.com/tag/oneplus-9/) and 9 Pro will let our users see the world around them through a unique lens,” said Hsiaohua Cheng, Head of Imaging at OnePlus.

The new Hasselblad XPan Mode offers the following features:

Aspect ratio of 65:21 – offering the same cinematic look as the actual Hasselblad XPan camera
Very wide mode – 2 focal lengths
Two of the classic focal lengths seen on the XPan, 30mm (cropped by UW) and 45 MM (main camera)
With over 20 megapixels, the camera is able to maintain a high-resolution photo, even after cropping in their images
Preview Box – In phone preview, users will see the same frame lines seen through the lens of an actual XPan camera
Animation of developing negative film after taking a shot
Two film simulation effects
Color and black & white – co-worked with Hasselblad to bring a unique B&W film
Apart from XPan Mode, the new OxygenOS update packs the following camera improvements and system optimizations:

Camera
Optimized HDR frame retrieving algorithms and reduced noise in multiple scenes
Fix the over-sharpening issues in auto mode scenarios
Improved stability of auto white balance in auto mode
Optimized auto white balance when shifting between the main and ultra-wide camera
Reduced over-brightening of images on Nightscape Mode
Improved the dynamic range in low-light conditions
Improved success rate when shooting moving objects
Updated the memory optimization solution and reduced the launch time of the native camera app by up to 50%
Reduced lag in camera preview and optimized the shutter lag in some scenarios
Security
Updated Android security patch to September 2021
System
Optimized the wireless charing experience
Fixed known issues and improved stability
The new OxygenOS update with Hasselblad XPan Mode has started rolling out to the OnePlus 9 and [OnePlus 9 Pro](https://www.xda-developers.com/tag/oneplus-9-pro/) units.

 

 

 

 TagsOnePlusOnePlus 9OnePlus 9 Pro[OxygenOS](https://www.xda-developers.com/tag/oxygenos/)
[XDA](https://www.xda-developers.com/) » [News Brief](https://www.xda-developers.com/category/xda-news/)[](https://www.xda-developers.com/author/kristinspradlin/)[](https://twitter.com/kishanvyas_55)[](https://www.xda-developers.com/author/kristinspradlin/) » OnePlus 9’s latest OxygenOS update brings many camera improvements and Hasselblad XPan mode

ABOUT AUTHOR
Kishan Vyas

[ Load Comments]()[](https://www.xda-developers.com/oppo-reno-7-india-launch-oppo-watch-free/)[](https://www.xda-developers.com/oppo-reno-7-india-launch-oppo-watch-free/)
LATEST XDA NEWS
[OPPO Reno 7 series lands in India alongside the OPPO Watch Free](https://www.xda-developers.com/oppo-reno-7-india-launch-oppo-watch-free/)[](https://www.xda-developers.com/paranoid-android-sapphire-alpha-2-android-12-mi-10t-pro-mi-10/)[](https://www.xda-developers.com/paranoid-android-sapphire-alpha-2-android-12-mi-10t-pro-mi-10/)
OPPO Reno 7 series lands in India alongside the OPPO Watch Free
 February 4, 2022
[Paranoid Android Sapphire Alpha 2 based on Android 12 is here for Xiaomi Mi 10, Mi 10T and Mi 10T Pro](https://www.xda-developers.com/paranoid-android-sapphire-alpha-2-android-12-mi-10t-pro-mi-10/)[](https://www.xda-developers.com/windows-11-media-player-beta-channel/)[](https://www.xda-developers.com/windows-11-media-player-beta-channel/)
Paranoid Android Sapphire Alpha 2 based on Android 12 is here for Xiaomi Mi 10, Mi 10T and Mi 10T Pro
 February 4, 2022
[New Windows 11 Media Player is now available to Insiders in the Beta channel](https://www.xda-developers.com/windows-11-media-player-beta-channel/)[](https://www.xda-developers.com/amazon-prime-price-increase/)[](https://www.xda-developers.com/amazon-prime-price-increase/)
New Windows 11 Media Player is now available to Insiders in the Beta channel
 February 3, 2022
[Amazon Prime’s price is increasing again, because Jeff Bezos needs more money](https://www.xda-developers.com/amazon-prime-price-increase/)[](https://www.xda-developers.com/surface-laptop-4-deal-feb-2022/)[](https://www.xda-developers.com/surface-laptop-4-deal-feb-2022/)
Amazon Prime’s price is increasing again, because Jeff Bezos needs more money
 February 3, 2022
[Get the Surface Laptop 4 with a Ryzen 7 CPU for $211 off today](https://www.xda-developers.com/surface-laptop-4-deal-feb-2022/)
Get the Surface Laptop 4 with a Ryzen 7 CPU for $211 off today
 February 3, 2022

XDA Developers was founded by developers, for developers. It is now a valuable resource for people who want to make the most of their mobile devices, from customizing the look and feel to adding new functionality.

[Are you a developer?](https://www.xda-developers.com/recognized-developer-program/) | [Terms of Service](https://www.xda-developers.com/xda-tos/)

This site is protected by reCAPTCHA and the Google [Privacy Policy](https://policies.google.com/privacy) and [Terms of Service](https://policies.google.com/terms) apply.

More info
[Contact](https://www.xda-developers.com/contact/)
[Advertise](https://www.xda-developers.com/advertise-with-xda/)
[About](https://www.xda-developers.com/about/)
[Suggest Content](https://www.xda-developers.com/suggest-content/)
[Security](https://www.xda-developers.com/xda-disclosure-policy/)
[Privacy Policy](https://www.xda-developers.com/xda-developers-privacy-policy/)

Useful Links
[Best Android Phones](https://www.xda-developers.com/best-android-phones/)
[How to Root](https://www.xda-developers.com/root/)
[Best Laptops](https://www.xda-developers.com/best-laptops/)
[How To Guides](https://www.xda-developers.com/how-to-do-everything-on-your-phone/)[](https://twitter.com/xdadevelopers)[](https://discord.gg/e4v8qtkcBw)[](https://www.facebook.com/xda.developers)[](https://www.youtube.com/user/xdadevelopers?sub_confirmation=1)[](https://t.me/xdadevelopershub)[](https://www.instagram.com/xdasocial/)

Copyright © XDA

We're Social

**Comment by riteshsp2000** [comment] 2022-02-09 14:57
Hey @lecoursen, I'll raise a PR fixing this.

**Comment by sarhm** [comment] 2022-02-09 16:30
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> 
> ### What part(s) of the article would you like to see updated?
> Information in the first paragraph regarding permissions required to be a code owner conflicts with the **CODEOWNERS Syntax** section.
> 
> ## Intro Paragraph
> > ****The people you choose as code owners must have write permissions for the repository.**** When the code owner is a team, that team must be visible and it must have write permissions, even if all the individual members of the team already have write permissions directly, through organization membership, or through another team membership.
> 
> ## CODEOWNERS Syntax
> > A CODEOWNERS file uses a pattern that follows most of the same rules used in gitignore files, with some exceptions. The pattern is followed by one or more GitHub usernames or team names using the standard @username or @org/team-name format. ****Users must have read access to the repository**** and teams must have explicit write access, even if the team's members already have access. You can also refer to a user by an email address that has been added to their account on GitHub.com, for example [user@example.com](mailto:user@example.com).
> 
> ### Additional information
> _No response_

**Comment by sarhm** [comment] 2022-02-09 19:40
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> 
> ### What part(s) of the article would you like to see updated?
> Information in the first paragraph regarding permissions required to be a code owner conflicts with the **CODEOWNERS Syntax** section.
> 
> ## Intro Paragraph
> > ****The people you choose as code owners must have write permissions for the repository.**** When the code owner is a team, that team must be visible and it must have write permissions, even if all the individual members of the team already have write permissions directly, through organization membership, or through another team membership.
> 
> ## CODEOWNERS Syntax
> > A CODEOWNERS file uses a pattern that follows most of the same rules used in gitignore files, with some exceptions. The pattern is followed by one or more GitHub usernames or team names using the standard @username or @org/team-name format. ****Users must have read access to the repository**** and teams must have explicit write access, even if the team's members already have access. You can also refer to a user by an email address that has been added to their account on GitHub.com, for example [user@example.com](mailto:user@example.com).
> 
> ### Additional information
> _No response_

**Closed** 2022-02-11 17:02 UTC
Labels: help wanted, good first issue, content, MLH fellowship
