### ISSUE TITLE
Improve table on the About billing for GitHub Actions page.

### ISSUE THREAD

**Issue by tschuett** [github/docs#22179] opened 2022-11-20 14:18 UTC
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates

### What part(s) of the article would you like to see updated?

The table below the Per minute rates for higher core counts is unreadable in my Safari. There are probably some line breaks missing.

**Comment by chrissygem42** [comment] 2022-11-20 17:59
Thank you!

________________________________________
From: tschuett ***@***.***>
Sent: Sunday, November 20, 2022 2:21:58 PM
To: github/docs
Cc: Subscribed
Subject: [github/docs] Improve table on the About billing for GitHub Actions page. (Issue #22179)

Code of Conduct

  *    I have read and agree to the GitHub Docs project's Code of Conduct<https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md>

What article on docs.github.com is affected?

https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates

What part(s) of the article would you like to see updated?

The table below the Per minute rates for higher core counts is unreadable in my Safari. There are probably some line breaks missing.

Additional information

No response

**Comment by HonkingGoose** [comment] 2022-11-21 11:25
I think this issue is a duplicate of this earlier issue:

- #22102

---

By the way, here's a screenshot of the affected page in production. I'm using Firefox `107.0` on macOS:

![messed-up-billing-table](https://user-images.githubusercontent.com/34918129/203038690-6e1cacc6-ea1a-4778-b9f4-4c882c5fdf7d.png)

**Comment by Aizmansor** [comment] 2022-11-21 14:56
Dihantar daripada telefon saya-------- Mesej asal --------Daripada: HonkingGoose ***@***.***>Tarikh: Isn, 21 Nov 2022, 7:26 PTGKepada: github/docs ***@***.***>Sk: Subscribed ***@***.***>Tajuk: Re: [github/docs] Improve table on the About billing for GitHub Actions page. (Issue #22179)
I think this issue is a duplicate of this earlier issue:
#22102

By the way, here's a screenshot of the affected page in production. I'm using Firefox 107.0 on macOS:

**Closed** 2022-11-21 15:55 UTC
Labels: content, triage

**Comment by cmwilson21** [comment] 2022-11-21 17:22
@tschuett Thanks for opening an issue to report this! ✨ 

@HonkingGoose Thanks for linking with the other information! ✨ 

We are looking at this internally. 💛
