### ISSUE TITLE
Expression function "contains" array example does not work

### ISSUE THREAD

**Issue by averikitsch** [github/docs#10239] opened 2021-09-22 19:31 UTC
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/expressions#contains

### What part(s) of the article would you like to see updated?

Currently the "Example using an array" for contains does not work as intended.
```
Example using an array
contains(github.event.issue.labels.*.name, 'bug')
```
To work I've updated it to 
```
contains(join(github.event.issue.labels.*.name, ', '),'bug')
```

My example:
```
on:
  pull_request:
    types: [labeled, unlabeled]


jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - run: |-
          echo ${{contains(join(github.event.pull_request.labels.*.name, ', '),'needs')}}
          echo ${{contains(github.event.pull_request.labels.*.name,'needs')}}
```

When I add the label "needs work", I see the print out
```
true
false
```

**Comment by ramyaparimi** [comment] 2021-09-23 13:08
@averikitsch 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment] 2021-09-23 20:31
Thanks for opening this issue! I'm not able to reproduce this. In my test case (copying your workflow), both expressions return true. (e.g. https://github.com/ske-test-org/test-org-repo/runs/3692553997?check_suite_focus=true) I'm going to close this issue, but feel free to reopen it with a link to a workflow run log that demos your experience.

![image](https://user-images.githubusercontent.com/25328854/134579592-267c00ea-fd65-473e-b870-af809d1e82e5.png)

**Closed by skedwards88** 2021-09-23 20:31 UTC
Labels: content, actions
