### ISSUE TITLE
Update GPG creation guide on Windows

### ISSUE THREAD

**Issue by NoNameProvided** [github/docs#6112] opened 2021-05-07 13:05 UTC
### What article on docs.github.com is affected?

After I completed the guide on how setup GPG commit signing on Windows git failed to sign any commits. I have followed the following articles:
- [Generating a new GPG key](https://docs.github.com/en/github/authenticating-to-github/generating-a-new-gpg-key)
- [Adding a new GPG key to your GitHub account](https://docs.github.com/en/github/authenticating-to-github/adding-a-new-gpg-key-to-your-github-account)
- [Telling Git about your signing key
](https://docs.github.com/en/github/authenticating-to-github/telling-git-about-your-signing-key)
  - in this page I read and did both section: the GPG and the X.509 one
  - I am on Windows and followed the Windows guide when applicable
  
After completing the steps git commit was broken with the following error:

```
gpg could not find identity matching specified user-id: <MY-SHORT-KEY-ID> 
```

After playing around the commands I have figured out that I have to specify the long certificate ID in `user.signingkey` to make it work. 

As extra information I am attaching a filtered version of my git config, to see what options enabled me to use GPG on Windows.

```
[user]
	email = NoNameProvided@users.noreply.github.com
	name = Attila Oláh
	signingkey = <MY-LONG-SIGN-KEY-ID>
	signkey = <MY-LONG-SIGN-KEY-ID>
[gpg "x509"]
	program = C:/Users/<my_user>/scoop/shims/smimesign
[commit]
	gpgsign = true
```

### What part(s) of the article would you like to see updated?

The parts where the article explains how to set the signing key needs to be updated to work on windows. Instead of specifying the short ID of the GPG key the long ID needs to be added from the following command.

```
gpg --list-secret-keys
```

### Additional information

n/a

**Comment by janiceilene** [comment] 2021-05-07 22:53
Thanks for opening an issue and giving detailed information about what you're seeing @NoNameProvided! I'll get this triaged for the team to take a look 👀

**Comment by felicitymay** [comment] 2021-05-13 11:43
Hi @NoNameProvided - thank you for the detailed information about the steps you took and the problem you encountered. it was really helpful and enabled me to follow your steps.

As far as I can tell, the steps tell you to list and use the long format of the GPG key:

```
gpg --list-secret-keys --keyid-format LONG
```

I followed the steps on Windows and have managed to set up commit signing. Looking at these articles, I was surprised to see `LONG` in capital letters as we usually use capital letters for text that is a placeholder for your own value. However, in this case it is an important part of the command, otherwise you only get the short key and encounter the problems that you found.

I *think* that perhaps what happened was that because `LONG` is in capital letters, you may have assumed that this wasn't part of the command and omitted it. Does that sound possible?

---

## Content design to address this issue

Update the two reusable sections of text used in these articles to make it clearer that the long form of the key identifier is needed.

- `data\reusables\gpg\copy-gpg-key-id.md`
- `data\reusables\gpg\list-keys-with-note.md`

In particular:

1. Update the explanatory text to mention the long form of the key or key identifier.
2. Change the command to: `gpg --list-secret-keys --keyid-format=long`

**Comment by thisthisandthat** [comment] 2021-05-14 21:24
#420

**Comment by codewithdev** [comment] 2021-05-27 13:23
@emilyistoofunky  I would like to work on this Issue :)

**Comment by janiceilene** [comment] 2021-05-28 23:02
@codewithdev I've assigned it to you! Let us know if you have any questions 🎉

**Comment by codewithdev** [comment] 2021-05-29 10:45
@janiceilene I just wanted to confirm that both `gpg --list-secret-keys --keyid-format LONG`  and `gpg --list-secret-keys --keyid-format= long` prompts the same result in the shell. Thus replacing

**Comment by felicitymay** [comment] 2021-06-02 09:37
Hi @codewithdev 👋🏻 

Thanks for looking into this issue and thinking about the best way to make the information clear for users ✨ 

> I just got surprised that both `gpg --list-secret-keys --keyid-format LONG` and `gpg --list-secret-keys --keyid-format= long` prompts the same result in the shell. Thus replacing the format `LONG` with `long` would catch the same thing.

That's a great point. I recommended the change to `gpg --list-secret-keys --keyid-format= long` to make it more difficult for users to overlook the need to request and use the long format of the GPG key ID in the procedures where these reusables are used. The current example is correct but I think the alternative is easier to follow. We often use capital letters to denote placeholder values, but here `LONG` is actually what you need to enter. I think this maybe the cause of this user's confusion.

> To avoid the complexity from the user's perspective, we can also add the `SHORT` or `short` keyid format that lets the user to display the chosen format of the key.

Reading your comment made me realize that I omitted to include links to articles where these reusables are used - sorry about this. They're both used in procedures where the user must get and use the long format of the GPG key ID. I think that the best way to make this clear is to update the explanatory text in the reusables to state that they need to use the long format of the key ID.

I think talking about the short form of the key ID in these reusables would make the procedural step more complicated and might even add more confusion. If you think that people need to know about both types of key identifier, I'd recommend adding a brief introduction before the procedure in [Generating a GPG key](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/generating-a-new-gpg-key#generating-a-gpg-key) to explain that GPG keys have both a short and a long identifier and that GitHub uses the long identifier.

**Comment by codewithdev** [comment] 2021-06-02 10:27
Thanks, @felicitymay for the clarification on the thread.✨
> The current example is correct but I think the alternative is easier to follow. We often use capital letters to denote placeholder values, but here `LONG` is actually what you need to enter. I think this may be the cause of this user's confusion.

Now I understood the differences that occur while drafting the change from `LONG` to `=long`. I will surely go ahead to make a  certain updation in the command.  

> think talking about the short form of the key ID in these reusables would make the procedural step more complicated and might even add more confusion. If you think that people need to know about both types of key identifier, I'd recommend adding a brief introduction before the procedure in [Generating a GPG key](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/generating-a-new-gpg-key#generating-a-gpg-key) to explain that GPG keys have both a short and a long identifier and that GitHub uses the long identifier.

That sounds interesting though. I know `SHORT` reusables are not mandatory as these make it hard to think about the usage and applications. By looking at the current changes it can be added as for knowledge, also I will add some context about which reusables GitHub supports.

**Comment by felicitymay** [comment] 2021-06-02 11:17
@codewithdev - Thinking about this more. 

I recommend you open a pull request with the first set of changes (described here: https://github.com/github/docs/issues/6112#issuecomment-840502883). When your pull request is open, we can look at the updated articles on staging. Then it will be easy to decide if we need to make any additional changes.

**Comment by codewithdev** [comment] 2021-06-02 18:46
@felicitymay Let me Know if this works :)

**Closed** 2021-06-03 07:37 UTC
Labels: Campus Experts + Docs program, content, help wanted, windows
