### ISSUE TITLE
`github` is duplicated in .github/workflows/check-broken-links-github-github.yml

### ISSUE THREAD

**Issue by jsoref** [github/docs#30785] opened 2023-12-21 01:10 UTC
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

.github/workflows/check-broken-links-github-github.yml

### What changes are you suggesting?

Remove one instance of `github` from https://github.com/github/docs/blob/10f8a4e855c10380f9e44f6c27e904d61756c38d/.github/workflows/check-broken-links-github-github.yml#L23

**Comment by jsoref** [comment] 2023-12-21 16:18
Nope. We can't, it's in a locked file and our PR will be killed by a 🤖.

**Comment by nguyenalex836** [comment] 2023-12-21 16:25
Thanks for the heads up on the locked file, @jsoref! Let me get this triaged for review ✨

**Comment by subatoi** [comment] 2023-12-27 08:59
Thanks for raising an issue! It looks a little odd, but this is as intended, so I'll go ahead and close this out.

**Closed by subatoi** 2023-12-27 08:59 UTC
Labels: content, waiting for review, administering a repo
