### ISSUE TITLE
LICENSE.rst is also supported

### ISSUE THREAD

**Issue by peterjc** [github/docs#3669] opened 2021-02-13 11:14 UTC
### What article on docs.github.com is affected?

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

### What part(s) of the article would you like to see updated?

Should mention ``LICENSE.rst`` too

### Additional information

See PR #3586

**Comment by IAMZevahc** [comment] 2021-02-15 15:18
Duplicate of #

**Comment by IAMZevahc** [comment] 2021-02-15 15:19
#3710

**Comment by IAMZevahc** [comment] 2021-02-15 15:19
Pull #3710

**Comment by peterjc** [comment] 2021-02-15 15:28
I disagree, #3710 is about MP4 files - nothing about LICENSE files. Was that a typo?

**Closed** 2021-03-04 19:15 UTC
