### ISSUE TITLE
Broken link on emoticon 'beetle' 

### ISSUE THREAD

**Issue by adityadees** [github/docs#9915] opened 2021-09-09 08:49 UTC
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Broken link on emoticon 'beetle'
[Link Issue](https://github.com/github/docs/blob/main/CONTRIBUTING.md#beetle-issues)

![image](https://user-images.githubusercontent.com/37553901/132654073-6bd3fc70-312d-4ee6-aebf-81172791d3db.png)

![image](https://user-images.githubusercontent.com/37553901/132653915-f4259a81-f274-4b09-9770-72af7d783831.png)

### What changes are you suggesting?

Replace with the new one maybe?

**Comment by rcowsill** [comment] 2021-09-09 14:24
It looks like this is a general issue with GitHub's markdown processing. `:beetle:` displays incorrectly in issues too:

:beetle:

It's included in the issue editor's emoji list, so I think it is still supposed to exist.

**Comment by ramyaparimi** [comment] 2021-09-09 16:57
@adityadees Looks like this issue has been fixed and I noticed that the 🪲 is rendering fine in the link provided. I am going  to close this issue now 💛  but please let us know if you still see this issue! 🐢 🐬

**Closed by ramyaparimi** 2021-09-09 16:57 UTC
Labels: content, triage

**Comment by rcowsill** [comment] 2021-09-10 13:30
This is strange, I still get the issue on the linked page, and in this thread when viewed on github.com, for example:

![comment](https://user-images.githubusercontent.com/42620235/132860869-44343a7d-e2a5-4156-9716-18ff1c3d54f4.png)

The email notification I received about that comment does render correctly in the same browser, however:

![email](https://user-images.githubusercontent.com/42620235/132860960-d2bc8ee8-dd09-446a-a620-0d286b210d04.png)

**Comment by ramyaparimi** [comment] 2021-09-13 17:18
Ah! That's strange! I still can't reproduce the issue. I wonder if it has to do with the type of browser and version. I am on MacOS 11.4. I use Firefox Version 91.0.2 (64-bit) and Google Chrome Version 93.0.4577.63.

I hope this information helps 🐬

**Comment by rcowsill** [comment] 2021-09-13 21:52
I'm using Firefox 92.0 on Windows and Linux. I tried Chrome 92.0 in a Windows 7 VM and got the same issue there too.

What seems to be happening is that the beetle image is missing from the server. It's supposed to be here:

https://github.githubassets.com/images/icons/emoji/unicode/1fab2.png

...but if I click that link I just get "Not Found". Maybe it's not a reliable repro due to caching, or perhaps it only works for GitHub staff.

Since it's happening in the markdown editor (not just the docs) I don't think this issue belongs in [github/docs](https://github.com/github/docs). I'm not sure where it should go, though. Any suggestions @ramyaparimi?

**Comment by ramyaparimi** [comment] 2021-09-14 17:11
@rcowsill I’d recommend contacting support to report the problem. Please be certain to include all combinations of browser (with detailed version information) and OS (with detailed version information) that you were able to reproduce the problem on 🐢 🐬
