### ISSUE TITLE
Checks API output text limit

### ISSUE THREAD

**Issue by NasAmin** [github/docs#2403] opened 2020-12-28 21:30 UTC
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/rest/reference/checks

### What part(s) of the article would you like to see updated?

The [Creating a Check section](https://docs.github.com/en/free-pro-team@latest/rest/reference/checks#create-a-check-run) describes the different parameters of creating the check. In particular, the `Output --> text` parameter. Recently, I become aware that the `output.text` is limited to 65k characters. Is this a hard limit?
What is the advice if we are providing a markup that exceeds the 65k limit? 
If there is a hard limit on `output.text` then IMHO it should be in the documentation plus some advice if larger data is needed in this field. Can it be a blob instead of a text field?

### Additional information
One might wonder why would you want to send so much data to a check output?
An example is reports for test results
An example of this could be creating a check for [unit test results](https://github.com/NasAmin/trx-parser).

**Comment by janiceilene** [comment] 2020-12-29 15:47
Thanks for opening an issue @NasAmin! I'll get this triaged for the team to take a look 👀

**Comment by somaticbeing** [comment] 2021-01-08 03:15
Find XYZ

**Comment by janiceilene** [comment] 2021-02-22 23:20
Just noticed this is a duplicate of https://github.com/github/docs/issues/3765! Closing this one in favor of the other one 😸

**Closed by janiceilene** 2021-02-22 23:20 UTC
Labels: ecosystem
