### ISSUE TITLE
Inconsistent documentation about GCR support for GITHUB_TOKEN

### ISSUE THREAD

**Issue by sleevi** [github/docs#5020] opened 2021-04-02 18:13 UTC
### What is the current behavior?

https://docs.github.com/en/packages/guides/migrating-to-github-container-registry-for-docker-images

currently states, under [Authenticating with the Container Registry](https://docs.github.com/en/packages/guides/migrating-to-github-container-registry-for-docker-images#authenticating-with-the-container-registry):
> To authenticate to GitHub Container Registry within a GitHub Actions workflow, use the GITHUB_TOKEN for the best security and experience.

and

> GitHub Container Registry now supports GITHUB_TOKEN for easy and secure authentication in your workflows. If your workflow is using a personal access token (PAT) to authenticate to ghcr.io, then we highly recommend you update your workflow to use GITHUB_TOKEN.

Under [Updating your GitHub Actions Workflow](https://docs.github.com/en/packages/guides/migrating-to-github-container-registry-for-docker-images#updating-your-github-actions-workflow), it conflictingly states:
> GitHub Container Registry does not support using GITHUB_TOKEN for your PAT so you must use a different custom variable, such as CR_PAT. For more information, see "Creating and storing encrypted secrets."

### What changes are you suggesting?

Given that GitHub Container Registry reportedly now supports `GITHUB_TOKEN`, presumably the updated workflow should recommend `GITHUB_TOKEN` instead of encouraging `CR_PAT` still.

**Comment by mesca216** [comment] 2021-04-03 00:46
[https://github.com/cop4520-btc/nodejs_service/projects/1#card-56813962](https://github.com/cop4520-btc/nodejs_service/projects/1#card-56813962) `
Duplicate of #`

**Comment by janiceilene** [comment] 2021-04-05 21:28
Thanks so much for opening an issue @sleevi! I'll get this triaged for the team to take a look 👀

**Comment by lee-dohm** [comment] 2021-04-22 14:45
Hello @sleevi! Thanks for bringing this to our attention 🙇‍♂️ 

We would welcome a PR from you (or anyone else interested) to fix this discrepancy.

Thanks again for your passion and interest in improving the GitHub Docs 💖

**Closed** 2021-05-18 09:31 UTC
Labels: actions, help wanted, packages
