### ISSUE TITLE
Slider not working properly.

### ISSUE THREAD

**Issue by nikunjvaghasiya** [github/docs#3230] opened 2021-01-27 12:33 UTC

**Comment by ajs256** [comment] 2021-01-27 15:40
Hey there @nikunjvaghasiya!

Thanks for opening an issue. Could you please edit your initial comment and fill out the issue template so the team can know what the problem is?

> Please note that I am not affiliated with the GitHub docs team.

**Comment by janiceilene** [comment] 2021-01-28 19:31
This issue is blank and appears have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions in [discussions](https://github.com/github/docs/discussions)!

**Closed by janiceilene** 2021-01-28 19:31 UTC
Labels: triage

**Comment by Jana-kasuar** [comment] 2021-01-28 19:34
Thanks a lot, very nice discusion and sites. Hey

Odesláno z aplikace Pošta<https://go.microsoft.com/fwlink/?LinkId=550986> pro Windows 10

Od: Janice<mailto:notifications@github.com>
Odesláno:čtvrtek 28. ledna 2021 20:32
Komu: github/docs<mailto:docs@noreply.github.com>
Kopie: Subscribed<mailto:subscribed@noreply.github.com>
Předmět: Re: [github/docs] Slider not working properly. (#3230)


This issue is blank and appears have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions in discussions<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgithub%2Fdocs%2Fdiscussions&data=04%7C01%7C%7Cb1fc452adeb1404e08ec08d8c3c36b80%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637474591370859249%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Z%2BOqO96se3wmuP20QDnPdsm60HC8dr2a7mvZnpPFZbs%3D&reserved=0>!
