### ISSUE TITLE
After contributing through fork, get flooded with hourly failed actions

### ISSUE THREAD

**Issue by corneliusroemer** [github/docs#13017] opened 2021-12-15 13:15 UTC
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The contribution experience when proposing changes to the docs through a Github PR

### What changes are you suggesting?

I contributed to docs. So I set up a fork for the PR to come from.

Now I get flooded with failed actions coming from the fork. I had to manually disable actions after discovering my email inbox was totally overwhelmed. This is not a good experience - it's almost a DOS attack. I might miss some important failed actions in the haystack.

![image](https://user-images.githubusercontent.com/25161793/146193191-c43e84fb-815f-44da-b6a0-c1515d770c20.png)

![image](https://user-images.githubusercontent.com/25161793/146193198-d4b33927-66b1-44d9-ac33-d02985eea193.png)

### Additional information

There seems to have been a related issue before, but it was apparently closed as resolved and it's also not necessarily identical: https://github.com/github/docs/issues/9190

This is my fork: https://github.com/corneliusroemer/docs/actions

Workaround: disable actions on fork here https://github.com/corneliusroemer/docs/settings/actions
![image](https://user-images.githubusercontent.com/25161793/146193092-8839fa45-09ac-41de-bfda-212904a38dab.png)

**Comment by AnilSeervi** [comment] 2021-12-15 14:05
I agree with @corneliusroemer. I didn't raise an issue thinking this was a fault from my side.

Until now I had unsubscribed to the notification from my fork, thanks for the workaround.

**Comment by Dlocc23** [comment] 2021-12-15 16:27
#13020

**Comment by Dlocc23** [comment] 2021-12-15 16:27
> ### Code of Conduct
> * [x]  I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> The contribution experience when proposing changes to the docs through a Github PR
> 
> ### What changes are you suggesting?
> I contributed to docs. So I set up a fork for the PR to come from.
> 
> Now I get flooded with failed actions coming from the fork. I had to manually disable actions after discovering my email inbox was totally overwhelmed. This is not a good experience - it's almost a DOS attack. I might miss some important failed actions in the haystack.
> 
> ![image](https://user-images.githubusercontent.com/25161793/146193191-c43e84fb-815f-44da-b6a0-c1515d770c20.png)
> 
> ![image](https://user-images.githubusercontent.com/25161793/146193198-d4b33927-66b1-44d9-ac33-d02985eea193.png)
> 
> ### Additional information
> There seems to have been a related issue before, but it was apparently closed as resolved and it's also not necessarily identical: #9190
> 
> This is my fork: https://github.com/corneliusroemer/docs/actions
> 
> Workaround: disable actions on fork here https://github.com/corneliusroemer/docs/settings/actions ![image](https://user-images.githubusercontent.com/25161793/146193092-8839fa45-09ac-41de-bfda-212904a38dab.png)

**Comment by ramyaparimi** [comment] 2021-12-15 21:24
@corneliusroemer Thank you for opening this issue. I am going to close this as this is a duplicate of this issue https://github.com/github/docs/issues/9190 💛

**Closed by ramyaparimi** 2021-12-15 21:24 UTC
Labels: content

**Comment by corneliusroemer** [comment] 2021-12-15 21:36
Thanks for reviewing @ramyaparimi. Isn't it confusing to close as duplicate if the duplicate is closed itself?

**Comment by ramyaparimi** [comment] 2021-12-15 21:51
@corneliusroemer an [issue has been already created internally](https://github.com/github/docs/issues/9190#issuecomment-931537012) for review 💛
