### ISSUE TITLE
`color-bg-inset` is showing in home page

### ISSUE THREAD

**Issue by amendezm** [github/docs#25451] opened 2023-05-08 16:32 UTC
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/

![image](https://github.com/github/docs/assets/26444448/6a4a11ed-5fb3-4580-af6b-bc80dee7a9a5)

![image](https://github.com/github/docs/assets/26444448/2dad7e5f-1025-4385-b242-3ff7cbb29895)

### What changes are you suggesting?

Remove `color-bg-inset` from home page

**Comment by cmwilson21** [comment] 2023-05-08 17:43
@amendezm Thanks for opening an issue! However, I am unable to reproduce this problem. Can you confirm that it is still an issue? If this is for the main GitHub site, it would be better to leave feedback [here](https://github.com/community/community/discussions). If it's specific to the Docs site, let me know in this issue and we will investigate further. 👍 

I'm going to go ahead and close this issue for now, but please let us know if you continue to experience this. 💛

**Closed by cmwilson21** 2023-05-08 17:43 UTC
Labels: content, triage
