### ISSUE TITLE
Documentation page "Creating a pull request from a fork" is wrong about permissions.

### ISSUE THREAD

**Issue by Zimmi48** [github/docs#24454] opened 2023-03-15 10:35 UTC
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

See https://github.com/github/docs/issues/24454#issuecomment-1472312209 for changes required

### What part(s) of the article would you like to see updated?

Currently, the top of the page says:

![[...] Who can use this feature: Anyone with write access to a repository can create a pull request from a user-owned fork. [...] Note: To open a pull request in a public repository, you must have write access to the head or the source branch or, for organization-owned repositories, you must be a member of the organization that owns the repository to open a pull request.](https://user-images.githubusercontent.com/1108325/225283148-cab8fd79-2b9d-404f-a297-b3538fe4a087.png)

But what is written on permissions is completely wrong. Anyone can open a pull request from a fork as long as the repository is public.

### Additional information

This confused a colleague learning about pull/merge requests.

**Comment by cmwilson21** [comment] 2023-03-15 14:05
@Zimmi48 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by isaacmbrown** [comment] 2023-03-16 13:16
Hi @Zimmi48, thanks for opening this PR! ✨ You're right that the permissions information appears to be misleading here. I'll look into this and come back with some recommended updates

**Comment by isaacmbrown** [comment] 2023-03-16 16:33
The confusion here is that the permissions statement is referring to the fact that you need write access to the _fork_ repository to create a PR from it.

We should make the following clarifications in https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork:

- Change the permissions statement to:
   `To create a pull request from a user-owned fork, you must have write access to the fork.`
- Change the note below the statement to:
   `To open a pull request in a public repository, you must have write access to the head or the source branch of the fork or, for organization-owned forks, you must be a member of the organization that owns the fork.`

@Zimmi48, if you'd be up for opening a PR to make this change, that would really help us out! Otherwise, I'm adding the `help wanted` label, so anyone else is welcome to make the fix too. 🚀

**Comment by Zimmi48** [comment] 2023-03-16 16:57
> The confusion here is that the permissions statement is referring to the fact that you need write access to the _fork_ repository to create a PR from it.

@isaacmbrown That's not even correct. To prove my point, I opened #24492 with a user account that does not have write access to my fork at Zimmi48/docs.

**Comment by isaacmbrown** [comment] 2023-03-16 17:17
Hi @Zimmi48, that is strange, I wasn't able to reproduce this. When I try to create a pull request from a user-owned fork of `github/docs`, to which I only have read access, I get the following error:

<img width="1303" alt="CleanShot 2023-03-16 at 17 14 59@2x" src="https://user-images.githubusercontent.com/101839405/225699796-e85e40c2-5af7-4be8-ae47-175161878bb6.png">

This is consistent with how a member of the product team describes the behavior. Could you confirm that you didn't add `coqbot` as a collaborator on `Zimmi48/docs`, so I can take this to the product team again?

**Comment by isaacmbrown** [comment] 2023-03-16 17:22
I confirmed this again with a different repository:

<img width="1219" alt="CleanShot 2023-03-16 at 17 22 03@2x" src="https://user-images.githubusercontent.com/101839405/225701352-d6450837-fe59-43f3-9889-326662dcf45b.png">

**Comment by Zimmi48** [comment] 2023-03-16 21:02
No, coqbot is not a collaborator on my fork:

![image](https://user-images.githubusercontent.com/1108325/225751573-ffa0b692-0593-49b1-8c5d-4357eddc8351.png)

I was not aware that this feature was not supposed to exist. I always assumed it was well-designed, since, e.g., the checkbox to give write access to the PR branch disappears in this case.

**Comment by isaacmbrown** [comment] 2023-03-17 09:52
Hi @Zimmi48, thanks for getting back to me. I looked into this further.

In general, you are right that there isn't a strict requirement to have write access to a fork in order to create a PR from it. However, it turns out there is quite a complex and changing set of rules that determine when you _can_ create a PR from a read-only fork, hence why we ran into different outcomes. These rules are intended to prevent spam and therefore not something we would want to document.

With that in mind, I suspect we will just remove the permissions statement here, since it's probably unnecessary and potentially confusing to document that you need read access to the fork. But so we can reach a decision with the product team and identify any other places in the docs that may need updating (as you identified in your PR), I'm going to transfer this issue to our internal repository so we can work on it there.

Thanks again for raising the issue and sorry for the confusion.

**Comment by isaacmbrown** [comment] 2023-03-17 10:51
Closing in favor of internal issue

**Closed by isaacmbrown** 2023-03-17 10:51 UTC
Labels: content, pull requests
