### ISSUE TITLE
Metadata syntax for GitHub Actions: `continue-on-error` is not documented for composite actions

### ISSUE THREAD

**Issue by woodruffw** [github/docs#35728] opened 2024-12-20 10:57 UTC
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions

### What part(s) of the article would you like to see updated?

The documentation for composite actions doesn't mention the `continue-on-error` field, which has the same semantics as it has in Workflow definitions.

This field *is* present in the JSON Schema for composite actions, however: <https://json.schemastore.org/github-action.json>.

It looks like this field was added to composite actions in 2022 (via https://github.com/actions/runner/pull/1763) but the documentation was never updated.

**Comment by nguyenalex836** [comment] 2024-12-20 17:20
@woodruffw Thank you for raising this issue! I'll get this triaged for review :sparkles: Our team will provide feedback regarding the best next steps for this issue - thanks for your patience! 💛

**Comment by janbrasna** [comment] 2024-12-26 20:44
Possibly duplicate of #32097

**Comment by nguyenalex836** [comment] 2024-12-26 21:30
@woodruffw It looks like @janbrasna is right - thank you for catching that, Jan! 💛 

I'll go ahead and close this issue given https://github.com/github/docs/issues/32097 has been labeled `help wanted`, but let us know if we've missed anything on our end ✨

**Closed by nguyenalex836** 2024-12-26 21:30 UTC
Labels: content, actions, waiting for review
