### ISSUE TITLE
[GitHub Desktop] Update Configuring Git for GitHub Desktop Flow

### ISSUE THREAD

**Issue by steveward** [github/docs#4033] opened 2021-02-26 18:29 UTC
### What article on docs.github.com is affected?

https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/configuring-git-for-github-desktop

### What part(s) of the article would you like to see updated?

GitHub Desktop v2.6.4 will have a new Git configuration flow that allows you to select an email address associated with your GitHub account from a dropdown list in `Preferences` -> `Git`. Users can also select the `Other` option to use a custom email address, and GitHub Desktop will warn them if the email is not associated with the currently logged in account. See https://github.com/desktop/desktop/pull/11566 for screenshots and details.

The current article has the flow of copying an email from your GitHub account in browser and then pasting it into GitHub Desktop. We can now simplify this article and remove steps 1-5 since GitHub Desktop will automatically pull down all of the emails associated with your GitHub account.

Additionally in v2.6.4 you can now select a per-repository local email address (stored in the repository's `.git/config`). See https://github.com/desktop/desktop/pull/11595 for the related PR. I'm open for ideas about the best way to present this. Is it something we tag to the end and then add the "In this article" side navigation?

/cc @billygriffin 

---

## Content design

It seems that the **Git** page of the Preferences/Options dialog has also gained a section for defining the default branch name for repositories created by GitHub Desktop, so the changes are a little larger than originally suggested.

[Configuring Git for GitHub Desktop](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/configuring-git-for-github-desktop)

- Add a short introduction explaining the options available to control how the application interacts with Git (the email address to use for commits and the name of the default branch for new repositories). Mention that this is stored in your global config and used for all repositories. Give it an H3 title something like "About your configuration for Git"
- Add a new H3 title before the existing content, something like "Configuring your commit details".
- Extend the introduction briefly to mention that you can override this information, where necessary, for individual repositories and link to the new article described below.
- In both the Mac and Windows procedure, delete steps 1-5 as these are no longer needed. The first step will now the the following reusables:
    - Mac: `{% data reusables.desktop.mac-select-desktop-menu %}`
    -  Windows: `{% data reusables.desktop.windows-choose-options %}`
- Update `{% data reusables.desktop.paste-email-git-config %}` and rename to reflect the new process of selecting an email address from a drop-down.
- Create a new H3 title for the new options for branch naming, maybe "Configuring your default branch for new repositories".
- Write a brief explanation of the "Default branch for new repositories" and what impact it has.
- Repeat the steps to open the **Git** page.
- Add a step for changing the default branch name.
- Repeat the save step.

For the ability to override the email address in the global configuration for an individual repository, I think this might make most sense as a new article under: [Working with your remote repository on GitHub or GitHub Enterprise](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise) - it seems somewhat related to changing the remote's URL.

- Create a new article called something like "Overriding the email GitHub Desktop uses for a repository". 
    - Base the new article on [Changing a remote's URL from GitHub Desktop](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/changing-a-remotes-url-from-github-desktop).
    - Add a brief introduction that explains that you can override the email address and name GitHub Desktop uses in commits to a repository.
    - Mention that by default GitHub Desktop uses the values defined in your Preferences/Options and link to the [Configuring Git for GitHub Desktop](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/configuring-git-for-github-desktop) article for more information.
    - Explain that this is stored in your Git configuration for the repository.
    - Maybe explain when you might want to do this.
    - Follow with the procedure for overriding the global value.

**Comment by janiceilene** [comment] 2021-03-01 22:31
Thanks so much for opening an issue @steveward! When does v2.6.4 ship? 

cc @myarb for 👀 since this should probably go on your squad's roadmap. They could also write a content design for this issue, then open it up here to make the changes ✨

**Comment by billygriffin** [comment] 2021-03-02 17:49
@janiceilene Thank you! 2.6.4 ships tomorrow, but we're fine with lagging docs since this is implemented in a way that will dramatically alleviate confusion relative to current state, instead of potentially adding to it. 😄

**Comment by walli55** [comment] 2021-03-04 01:20
Duplicate of #

**Comment by felicitymay** [comment] 2021-05-13 13:08
@steveward and @billygriffin  - apologies for the delay in getting to this issue.

I've installed GitHub Desktop and looked at the new options. I've updated the OP with a content design plan that covers both the changes you mention above as well as the new section for defining the name for the default branch in new repositories.

**Closed** 2022-06-03 14:58 UTC
Labels: help wanted, content, core
