### ISSUE TITLE
fix github-action dependabot directory

### ISSUE THREAD

**Issue by KonradHoeffner** [github/docs#28102] opened 2023-09-08 10:57 UTC
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

### What part(s) of the article would you like to see updated?

According to <https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions>, workflow files must always be stored in `.github/workflows`. Thus the directory for dependabot should be adjusted accordingly.

The current way this is written is confusing:

```yaml
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```

```yaml
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
```

If this is indeed correct as it is, please explain why.

**Comment by cmwilson21** [comment] 2023-09-08 21:52
@KonradHoeffner Thank you for opening an issue and linking it to your PR! ✨

**Comment by ME3149235472** [comment] 2023-09-09 11:44
https://github.com/github/haikus-for-codespaces/pull/241#issuecomment-1712489281
Duplicate of # 🌹🕸️

**Comment by am-stead** [comment] 2023-09-11 09:41
Hi @KonradHoeffner, 
closing this issue as per my response [here](https://github.com/github/docs/pull/28103#issuecomment-1713531420).✨
Thanks again for taking the time to raise this question.💛

**Closed by am-stead** 2023-09-11 09:41 UTC
Labels: content
