### ISSUE TITLE
GitHub Copilot ReSharper config, adjust instructions

### ISSUE THREAD

**Issue by ceciliasharp** [github/docs#29919] opened 2023-11-13 11:58 UTC
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/copilot/configuring-github-copilot/configuring-github-copilot-in-your-environment

### What part(s) of the article would you like to see updated?

With Visual Studio selected and the section "Configuring ReSharper for GitHub Copilot". Point 1 is showing Tools and Option both in text and image but you will not find the setting there, it is located under ReSharper Optinos.

**Comment by hubwriter** [comment] 2024-01-19 12:40
Closing this as a duplicate of https://github.com/github/docs/issues/31013

We now have a PR to fix this: https://github.com/github/docs/pull/31025

**Closed by hubwriter** 2024-01-19 12:40 UTC
Labels: content, waiting for review, copilot
